IPD418	CALIDAD DE ENERGIA EN SIST. IND. CON CONV. EST.	ELECTRONICA	1	PONTT OLIVARES JORGE ANTONIO	20	Ver horario
MAT035	PROBABILIDAD Y ESTADÍSTICA PARA INGENIERÍA	MATEMATICA	1	TAPIA CARO JOSE ANDRES	40	Ver horario
BIE001	ACTIVIDAD NO ACADEMICA	DIRECCION DE ESTUDIO	1	VILLALOBOS PINO MARTIN	1	Ver horario
ACTPPI	ACTIVIDAD PROGRAMA PRELIMINAR PARA INGENIERÍA	V.R.A.	1	MORA AGUIRRE CELIN	80	Ver horario
ICN262	ADMINISTRACION DE EMPRESAS	INDUSTRIAS	1	DEL REAL FERNANDEZ GLORIA	40	Ver horario
 	2	DEL REAL FERNANDEZ GLORIA	40	Ver horario
 	3	DEL REAL FERNANDEZ GLORIA	40	Ver horario
 	4	DEL REAL FERNANDEZ GLORIA	40	Ver horario
IWQ272	ADMINISTRACION DE LA CALIDAD	INGENIERÍA QUíMICA Y AMBIENTAL	1	CARVAJAL DEL VILLAR HUMBERTO	45	Ver horario
CON390	ADMINISTRACION DE LA CONSTRUCCION	OBRAS CIVILES	1	LAGOS PERALTA FRANCISCO OMAR	50	Ver horario
ICN345	ADMINISTRACION DE LA PRODUCCION	INDUSTRIAS	1	SEBALLOS PALMA EDGARDO LUIS	40	Ver horario
 	2	ORTUZAR MATURANA RODRIGO IVAN	40	Ver horario
 	3	DIEZ BENNEWITZ MIGUEL PABLO	40	Ver horario
ICS751	ADMINISTRACION GENERAL	INGENIERÍA COMERCIAL	1	NARANJO TAPIA ALBERTO	40	Ver horario
 	5	PEREDA PRADO PAULINA ANDREA	40	Ver horario
ICS111	ADMINISTRACIÓN DE EMPRESAS	INGENIERÍA COMERCIAL	1	ESPINOZA CRISTIA JUAN FELIPE	40	Ver horario
 	2	CONTRERAS BARRAZA NICOLAS ESTEBAN	40	Ver horario
 	3	CONTRERAS BARRAZA NICOLAS ESTEBAN	40	Ver horario
 	4	DROGUETT MEGE PAULA	40	Ver horario
 	5	ESPINOZA CRISTIA JUAN FELIPE	40	Ver horario
TEL342	ADMINISTRACIÓN DE REDES DE COMPUTADORES	ELECTRONICA	1	TORRES YARZA JOSE GABRIEL	25	Ver horario
PII428	ADMINISTRACIÓN ESTRATÉGICA DE MARCA	INDUSTRIAS	1	FERNANDEZ ROBIN ERNESTO CRISTOBAL	20	Ver horario
HIW111	ALEMÁN NIVEL ELEMENTAL	ESTUDIOS HUMANISTICOS	1	WATSON ROJAS MARIA ANGELICA	20	Ver horario
HIW110	ALEMÁN NIVEL PRINCIPIANTE	ESTUDIOS HUMANISTICOS	1	WATSON ROJAS MARIA ANGELICA	20	Ver horario
MAT210	ALGEBRA LINEAL	MATEMATICA	1	MONTERO SILVA PEDRO PABLO	40	Ver horario
INF221	ALGORITMOS Y COMPLEJIDAD	INFORMATICA	1	VON BRAND SKOPNIK HORST	40	Ver horario
MAT410	ANALISIS CONVEXO	MATEMATICA	1	GAJARDO ADARO PEDRO RODRIGO	40	Ver horario
ICQ373	ANALISIS DE PROCESOS QUIMICOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	BORZONE SILVA LUIS ANDRES	40	Ver horario
ELI347	ANALISIS DE SISTEMAS DE POTENCIA II	INGENIERÍA ELÉCTRICA	1	BUSTOS OBREGON JULIAN	40	Ver horario
ELO104	ANALISIS DE SISTEMAS LINEALES	ELECTRONICA	1	VARGAS PARRA FRANCISCO JAVIER	60	Ver horario
CIV234	ANALISIS ESTRUCTURAL	OBRAS CIVILES	1	JENSEN VELASCO HECTOR ANTONIO	100	Ver horario
MAT225	ANALISIS I	MATEMATICA	1	GAJARDO ADARO PEDRO RODRIGO	40	Ver horario
QUI320	ANALISIS INSTRUMENTAL	QUIMICA	1	TESSINI ORTIZ CATHERINE VALESKA	40	Ver horario
QUI325	ANALISIS INSTRUMENTAL	QUIMICA	1	TESSINI ORTIZ CATHERINE VALESKA	40	Ver horario
MAT277	ANALISIS NUM.DE ECUAC.EN DERIVADAS PARCIALES	MATEMATICA	1	KARKULIK . MICHAEL	40	Ver horario
MAT270	ANALISIS NUMERICO	MATEMATICA	1	KARKULIK . MICHAEL	50	Ver horario
 	2	AGUILA FUMEY RAUL	60	Ver horario
 	3	NARANJO PEÑALOZA CESAR IGNACIO	50	Ver horario
 	4	NN	60	Ver horario
MAT274	ANALISIS NUMERICO II	MATEMATICA	1	NARANJO PEÑALOZA CESAR IGNACIO	40	Ver horario
QUI376	ANALISIS QUIMICO INSTRUMENTAL II	QUIMICA	1	TESSINI ORTIZ CATHERINE VALESKA	40	Ver horario
IWQ214	ANALISIS Y DISEÑO DE EXPERIM. INDUSTRIALES	INGENIERÍA QUíMICA Y AMBIENTAL	1	BERGH CONTARDO NICOLAS ALEJAND	40	Ver horario
ELO349	ANTENAS Y PROPAGACIÓN	ELECTRONICA	1	PIZARRO TORRES FRANCISCO	40	Ver horario
IAO262	ANÁLISIS APROXIMADO	ARQUITECTURA	1	FLORES GUTIERREZ ISAAC	40	Ver horario
MRA404	ANÁLISIS CRÍTICO PROYECTOS DE INTERVENCIÓN	ARQUITECTURA	1	HURTADO SALDIAS MARCELA	20	Ver horario
MAT269	ANÁLISIS ESTADÍSTICO MULTIVARIADO	MATEMATICA	1	OSORIO SALGADO FELIPE ALBERTO	40	Ver horario
MAT227	ANÁLISIS III	MATEMATICA	1	HERMOSILLA JIMENEZ CRISTOPHER ADRIAN	40	Ver horario
PII436	ANÁLISIS MULTIVARIADO PARA MARKETING	INDUSTRIAS	1	FERNANDEZ ROBIN ERNESTO CRISTOBAL	20	Ver horario
IPO440	ANÁLISIS Y DISEÑO DE PAVIMENTOS AVANZADO	OBRAS CIVILES	1	SALSILLI MURUA RICARDO ALEJANDRO	20	Ver horario
INF236	ANÁLISIS Y DISEÑO DE SOFTWARE	INFORMATICA	1	PONCE MELLA FRANCISCO LEONARDO	60	Ver horario
PII437	ANÁLISIS Y MÉTRICAS DE MARKETING	INDUSTRIAS	1	FERNANDEZ ROBIN ERNESTO CRISTOBAL	20	Ver horario
INF320	APLICACIONES MÓVILES	INFORMATICA	1	CHAU CHAN CHIHAU ANDRES	40	Ver horario
IPD440	APRENDIZAJE DE MAQUINAS	ELECTRONICA	1	ARAYA LOPEZ MAURICIO ALEJANDRO	20	Ver horario
INF245	ARQUITECTURA Y ORGANIZACIÓN DE COMPUTADORES	INFORMATICA	1	CAÑAS ROBLES JAVIER	60	Ver horario
HRW200	ARTE E INGENIERIA	ESTUDIOS HUMANISTICOS	1	AYALA VELOSO JUAN GONZALO	40	Ver horario
MRA450	ASENTAMIENTOS TRADICIONALES	ARQUITECTURA	1	CARRASCO WALBURG CAROLINA ANDREA	20	Ver horario
EFI102	ATLETISMO	DEFIDER	1	GONZALEZ VERGARA MIGUEL ALEJANDRO	30	Ver horario
 	2	GONZALEZ VERGARA MIGUEL ALEJANDRO	30	Ver horario
ICM363	AUTOMATIZACION	INGENIERÍA MECÁNICA	1	BREGANTE BACELLI ANDRES TOMAS	18	Ver horario
 	2	BREGANTE BACELLI ANDRES TOMAS	10	Ver horario
 	4	BREGANTE BACELLI ANDRES TOMAS	14	Ver horario
ELO372	AUTOMATIZACION INDUSTRIAL	ELECTRONICA	1	OLIVARES SALINAS MANUEL	50	Ver horario
AYF129	AYUD.FIS.129	FISICA	1		0	Ver horario
AYF110	AYUD.FIS.GRAL.I	FISICA	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
 	4		0	Ver horario
 	5		0	Ver horario
 	6		0	Ver horario
 	7		0	Ver horario
 	8		0	Ver horario
 	9		0	Ver horario
 	10		0	Ver horario
 	11		0	Ver horario
 	12		0	Ver horario
 	13		0	Ver horario
 	14		0	Ver horario
AYF120	AYUD.FIS.GRAL.II	FISICA	1		0	Ver horario
 	2		0	Ver horario
 	3	NN	0	Ver horario
 	4		0	Ver horario
 	5		0	Ver horario
 	6		0	Ver horario
 	7		0	Ver horario
AYF130	AYUD.FIS.GRAL.III	FISICA	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
 	4		0	Ver horario
 	5		0	Ver horario
AYF140	AYUD.FIS.GRAL.IV	FISICA	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
AYQ021	AYUD.QCA.BASICA-CIVILES	QUIMICA	1	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
 	2	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
 	3	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
 	4	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
 	5	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
 	6	NN	30	Ver horario
 	7	NN	30	Ver horario
 	8	NN	30	Ver horario
 	9	REVECO OLIVARES PATRICIO	40	Ver horario
 	10	REVECO OLIVARES PATRICIO	30	Ver horario
AYQ100	AYUD.QCA.GRAL.	QUIMICA	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
 	4		0	Ver horario
AYQ010	AYUD.QUIMICA Y SOCIEDAD	QUIMICA	1	NN	30	Ver horario
 	2	NN	0	Ver horario
 	3	NN	30	Ver horario
 	4	NN	30	Ver horario
 	5	NN	30	Ver horario
 	6	NN	30	Ver horario
 	7	NN	30	Ver horario
 	10	NN	30	Ver horario
 	16	NN	30	Ver horario
 	17	NN	30	Ver horario
 	22	NN	30	Ver horario
AYF119	AYUDANTIA FIS119	FISICA	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
IQA126	BALANCE DE MATERIA	INGENIERÍA QUíMICA Y AMBIENTAL	1	SIMPSON RIVERA RICARDO JOSE	40	Ver horario
INF239	BASES DE DATOS	INFORMATICA	1	REYES COVARRUBIAS CECILIA	80	Ver horario
INF325	BASES DE DATOS AVANZADAS	INFORMATICA	1	NN	40	Ver horario
INF303	BASES DE DATOS PARA LA GESTIÓN	INFORMATICA	1	NN	40	Ver horario
 	2	BIELENBERG GUZMAN MABEL A.	40	Ver horario
 	3	MONTENEGRO TAPIA GABRIELA PATRICIA	40	Ver horario
 	4	VEGA TORO JACOB FELIPE	40	Ver horario
 	5	LAZO ROBAINA YOSLANDY	40	Ver horario
INF330	BASES TECNOLOGICAS PARA LA INTELIGENCIA DE NEGOCIO	INFORMATICA	1	BANZ RAMIREZ FERNANDO	40	Ver horario
IWC260	BENEFICIO DE MINERALES	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	SERRANO GONZALEZ YARIELBA KATERINE	0	Ver horario
QUI250	BIOQUIMICA	QUIMICA	1	SEEGER PFEIFFER MICHAEL	50	Ver horario
ICM323	BOMBAS Y COMPRESORES	INGENIERÍA MECÁNICA	1	ESPINOZA SILVA JAIME	40	Ver horario
EFI104	BUCEO	DEFIDER	1	NN	40	Ver horario
EFI103	BÁSQUETBOL	DEFIDER	1	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
 	2	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
 	3	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
 	4	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
ELO250	CAMPOS ELECTROMAGNETICOS	ELECTRONICA	1	OLIVARES VELIZ RICARDO	40	Ver horario
 	2	DERPICH MUSA MILAN STEFAN	40	Ver horario
FIS221	CAMPOS ELECTROMAGNETICOS II	FISICA	1	SIDDIKOV . MARAT	40	Ver horario
ELI370	CENTRALES ELECTRICAS TERMICAS	INGENIERÍA ELÉCTRICA	1	HINOJOSA MATEUS VICTOR HUGO	20	Ver horario
CERT01	CERTAMEN	DIRECCION DE ESTUDIO	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
 	4	NN	0	Ver horario
 	5		0	Ver horario
 	6	NN	0	Ver horario
 	7	NN	0	Ver horario
 	8	NN	0	Ver horario
 	9		0	Ver horario
 	10		0	Ver horario
 	11		0	Ver horario
 	12		0	Ver horario
 	13		0	Ver horario
 	14		0	Ver horario
 	15		0	Ver horario
 	16		0	Ver horario
 	17		0	Ver horario
 	18		0	Ver horario
 	19		0	Ver horario
 	20		0	Ver horario
 	21		0	Ver horario
 	22		0	Ver horario
 	23		0	Ver horario
 	24	NN	0	Ver horario
 	25	NN	0	Ver horario
 	26	NN	0	Ver horario
 	27	NN	0	Ver horario
 	28	NN	0	Ver horario
 	29		0	Ver horario
 	30		0	Ver horario
 	31		0	Ver horario
 	32		0	Ver horario
 	33		0	Ver horario
 	34		0	Ver horario
 	35		0	Ver horario
 	39		0	Ver horario
 	40		0	Ver horario
 	44		0	Ver horario
 	46		0	Ver horario
 	48	NN	0	Ver horario
MIN103	CIENCIA AMBIENTAL	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	VEGA FAUNDEZ ABRAHAM DEL CARMEN	40	Ver horario
MET120	CIENCIA DE MATERIALES	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	AGUILAR RAMIREZ CLAUDIO EDUARDO	40	Ver horario
HRW170	CIENCIA TECN, Y SOC, SIGLO XX	ESTUDIOS HUMANISTICOS	1	IOMMI AMUNATEGUI XIMENA	40	Ver horario
MET332	CINÉTICA METALÚRGICA Y DISEÑO DE REACTORES	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	CASAS DE PRADA JESUS MANUEL	45	Ver horario
HFW139	CIVILIZACIONES PRECOLOMBINAS	ESTUDIOS HUMANISTICOS	1	RAMIREZ ALIAGA JOSE MIGUEL	20	Ver horario
MATE08	COMPLEMENTOS DE ÁLGEBRA Y CÁLCULO	MATEMATICA	1	SZANTO NAREA IVAN	40	Ver horario
 	1	GONZALEZ YAÑEZ BETSABE DEL CARMEN	40	Ver horario
 	1	BRICEÑO VALENCIA VERONICA ESTHER	40	Ver horario
MET244	COMPORTAMIENTO MECÁNICO DE MATERIALES	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	DE BARBIERI BOERO FLAVIO ANDRES	40	Ver horario
HRW100	COMPORTAMIENTO ORGANIZACIONAL	ESTUDIOS HUMANISTICOS	1	PRIETO PARRA MARIA EUGENIA	40	Ver horario
ILI285	COMPUTACION CIENTIFICA I	INFORMATICA	1	TORRES LOPEZ CLAUDIO	40	Ver horario
INF285	COMPUTACIÓN CIENTÍFICA	INFORMATICA	1	TORRES LOPEZ CLAUDIO	40	Ver horario
 	2	SANHUEZA ROMAN ARIEL OMAR	40	Ver horario
INF351	COMPUTACIÓN DE ALTO DESEMPEÑO	INFORMATICA	1	SALINAS EVANGELISTA ALVARO SIMON	40	Ver horario
IDP215	CONCEPCION DE PRODUCTOS	Ingeniería en Diseño	1	ORELLANA OLGUIN NICOLAS	40	Ver horario
IAO261	CONCEPTOS DE ESTRUCTURAS	ARQUITECTURA	1	BREYTMANN SCHULZE MATTHIAS ALEXANDER	60	Ver horario
CON222	CONSTRUCCION DE OBRAS CIVILES	OBRAS CIVILES	1	CANCINO ARAYA FERNANDO	60	Ver horario
CON220	CONSTRUCCION I	OBRAS CIVILES	1	SANCHEZ DROGUETT EDUARDO GONZALO	50	Ver horario
CON232	CONSTRUCCIONES SISMORRESISTENTE	OBRAS CIVILES	1	TOBAR RAMOS RENE ENRIQUE	60	Ver horario
ICS143	CONTABILIDAD DE GESTIÓN	INGENIERÍA COMERCIAL	1	PARDO MENESES RODRIGO MANUEL	40	Ver horario
ICS141	CONTABILIDAD FINANCIERA	INGENIERÍA COMERCIAL	1	CARO CAMPOS MARCELA ELISABETH	40	Ver horario
 	2	PEREZ LAGOS CRISTIAN RODRIG	40	Ver horario
 	3	CAMPOS JAQUE ZOCIMO JOSE	40	Ver horario
 	4	MUÑOZ DIAZ PABLO ANDRES	40	Ver horario
IPD467	CONTROL ADAPTIVO	ELECTRONICA	1	OLIVARES SALINAS MANUEL	20	Ver horario
ELO270	CONTROL AUTOMATICO I	ELECTRONICA	1	SUAREZ SOTOMAYOR ALEJANDRO	80	Ver horario
ELO370	CONTROL AUTOMATICO II	ELECTRONICA	1	ROJAS REISCHEL RICARDO	40	Ver horario
IPD416	CONTROL AVANZADO DE ACCIONAMIENTOS ELECTRICOS	ELECTRONICA	1	SILVA JIMENEZ CESAR ARMANDO	20	Ver horario
ELO386	CONTROL DE ACCIONAMIENTOS ELÉCTRICOS	ELECTRONICA	1	SILVA JIMENEZ CESAR ARMANDO	40	Ver horario
MAT436	CONTROL DE ECUACIONES DIF. PARCIALES	MATEMATICA	1	GUZMAN MELENDEZ PATRICIO RICARDO	40	Ver horario
MAT534	CONTROL DE ECUACIONES EN DERIVADAS PARCIALES (EDP)	MATEMATICA	1	GUZMAN MELENDEZ PATRICIO RICARDO	40	Ver horario
ILQ351	CONTROL DE PROCESOS INDUSTRIALES	INGENIERÍA QUíMICA Y AMBIENTAL	1	BABAROVICH HANSEN VICTOR PEDRO	40	Ver horario
ELI220	CONVERSION ELECTROMECANICA DE ENERGIA	INGENIERÍA ELÉCTRICA	1	ANGULO CARDENAS ALEJANDRO ALBER	40	Ver horario
PII426	CONVERSIÓN DE ENERGÍAS CONVENCIONALES	INDUSTRIAS	1	FUENTES CASTILLO ANDRES HERNAN	20	Ver horario
ICS026	CREACION DE EMPRESAS	INGENIERÍA COMERCIAL	1	NN	40	Ver horario
 	2	NN	40	Ver horario
HRW104	CRECIMIENTO Y DESARROLLO PERSONAL	ESTUDIOS HUMANISTICOS	1	VALLE SANGUINETTI CARLA ROSSINA	40	Ver horario
 	2	VALLE SANGUINETTI CARLA ROSSINA	40	Ver horario
 	3	MUCIENTES ARELLANO GLORIA DEL CARMEN	40	Ver horario
 	4	TOLEDO DELGADO DINO MAURICIO	40	Ver horario
 	5	TOLEDO DELGADO DINO MAURICIO	40	Ver horario
 	6	PRIETO PARRA MARIA EUGENIA	40	Ver horario
 	7	PRIETO PARRA MARIA EUGENIA	40	Ver horario
MATE25	CÁLCULO DIFERENCIAL	MATEMATICA	1	ROLDAN CONTRERAS FERNANDO MARCELO	40	Ver horario
 	1	OLIVARES BARRIENTOS MIGUEL ANGEL	40	Ver horario
 	2	CONTRERAS BARRAZA FABIAN	40	Ver horario
 	2	ROLDAN CONTRERAS FERNANDO MARCELO	40	Ver horario
 	3	TAPIA CARO JOSE ANDRES	40	Ver horario
MAT071	CÁLCULO EN UNA VARIABLE	MATEMATICA	1	TOLEDO TORRES PATRICIO ALEJANDRO	40	Ver horario
 	1	TORRES CABEZAS VICTOR GABRIEL	40	Ver horario
 	2	GALVEZ DIAZ SEBASTIAN ANDRES	40	Ver horario
 	2	TOLEDO TORRES PATRICIO ALEJANDRO	40	Ver horario
MATE26	CÁLCULO INTEGRAL	MATEMATICA	1	VILLAR SEPULVEDA EDGARDO ENRIQUE	40	Ver horario
 	1	OLIVARES BARRIENTOS MIGUEL ANGEL	40	Ver horario
HFW138	DESARROLLO EN LATINOAMÉRICA	ESTUDIOS HUMANISTICOS	1	CASANUEVA IOMMI MANUEL ANDRES	20	Ver horario
ICN337	DESARROLLO Y CONTROL DE PROYECTOS	INDUSTRIAS	1	MOYA ALFARO JOHANA SOLANGE	40	Ver horario
 	2	AMESTICA HERNANDEZ GONZALO DAVID	40	Ver horario
ICS024	DESARROLLO Y CONTROL DE PROYECTOS	INGENIERÍA COMERCIAL	1	GUAJARDO SALAS JORGE CRISTIAN	40	Ver horario
CIV103	DIBUJO EN INGENIERÍA CIVIL	OBRAS CIVILES	1	VARAS LEIVA ELOY GILBERTO	45	Ver horario
 	2	VARAS LEIVA ELOY GILBERTO	45	Ver horario
IWM179	DIBUJO Y TALLER MECANICO	INGENIERÍA MECÁNICA	1	MIRANDA VIVANCO HUMBERTO ENRIQUE	40	Ver horario
 	2	MIRANDA VIVANCO HUMBERTO ENRIQUE	40	Ver horario
ELO371	DINAMICA DE PROCESOS INDUSTRIALES	ELECTRONICA	1	RAMIREZ ESTAY HECTOR MIGUEL	40	Ver horario
MEC252	DINÁMICA	INGENIERÍA MECÁNICA	1	ROJAS GONZALEZ FERNANDO	40	Ver horario
IPD468	DINÁMICA DE SISTEMAS	ELECTRONICA	1	RAMIREZ ESTAY HECTOR MIGUEL	20	Ver horario
IPD462	DISEÑO AVANZADO DE SISTEMAS DE CONTROL	ELECTRONICA	1	AGÜERO VÁSQUEZ JUAN CARLOS	20	Ver horario
ICQ341	DISEÑO DE PROCESOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	NUÑEZ MUÑOZ PATRICIO	40	Ver horario
ILQ261	DISEÑO DE REACTORES	INGENIERÍA QUíMICA Y AMBIENTAL	1	BORZONE SILVA LUIS ANDRES	40	Ver horario
IPO443	DISEÑO DE VIADUCTOS	OBRAS CIVILES	1	BAZAEZ GALLARDO RAMIRO ANDRES GABRIE	20	Ver horario
IDP102	DISEÑO EN INGENIERIA	Ingeniería en Diseño	1	NIKULIN CHANDIA CHRISTOPHER	40	Ver horario
CIV370	DISEÑO GEOMÉTRICO Y CAPACIDAD VIAL	OBRAS CIVILES	1	NN	60	Ver horario
ICM381	DISEÑO MECANICO	INGENIERÍA MECÁNICA	1	GUROVICH ALBALA RAUL	40	Ver horario
ELO329	DISEÑO Y PROGRAMACION ORIENTADOS A OBJETOS	ELECTRONICA	1	GONZALEZ VALENZUELA AGUSTIN JOSE	48	Ver horario
 	2	NETTLE VACHER CRISTOBAL JESUS	40	Ver horario
ICN312	ECONOMETRIA	INDUSTRIAS	1	AHUMADA ESCOBAR MAURICIO	40	Ver horario
 	2	VILLALOBOS TORRES HUMBERTO MARCELO	40	Ver horario
ICS013	ECONOMETRIA	INGENIERÍA COMERCIAL	1	ORTEGA . JORGE AMILCAR	40	Ver horario
IMQ200	ECONOMIA AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	GUERRA ALARCON LEONARDO	40	Ver horario
ICS731	ECONOMIA I	INGENIERÍA COMERCIAL	1	SANCHEZ GIRALDEZ RODRIGO LUIS	40	Ver horario
ICS733	ECONOMIA I-A	INGENIERÍA COMERCIAL	1	SANCHEZ GIRALDEZ RODRIGO LUIS	45	Ver horario
 	2	KERRIGAN RICHARD GEORGE	45	Ver horario
 	3	SANCHEZ GIRALDEZ ANDRES CIRO	45	Ver horario
 	4	ERICES GARCIA CAROLINA MARCELA	45	Ver horario
 	5	KERRIGAN RICHARD GEORGE	45	Ver horario
IWN170	ECONOMIA I-A	INDUSTRIAS	1		0	Ver horario
ICS732	ECONOMIA II	INGENIERÍA COMERCIAL	1	VICENCIO GAVILAN PATRICIO	40	Ver horario
ICS030	ECONOMIA INTERNACIONAL	INGENIERÍA COMERCIAL	1	GATICA SILVA MACARENA	40	Ver horario
ICS867	ECONOMÍA SOCIAL	INGENIERÍA COMERCIAL	1	CEA VALENCIA JORGE MAURICIO	40	Ver horario
IQA101	ECOSISTEMAS Y BIODIVERSIDAD	INGENIERÍA QUíMICA Y AMBIENTAL	1	MERY ARAYA CAMILA DEL PILAR	40	Ver horario
MAT551	ECUACIONES DIFERENCIALES PARCIALES	MATEMATICA	1	QUAAS BERGER ALEXANDER	40	Ver horario
EFI100	EDUCACIÓN FÍSICA I (DAMAS Y VARONES)	DEFIDER	1	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	2	JONES JOFRE JENNIFER MAKARENA	30	Ver horario
 	3	HECHT CHAU GERNOT	30	Ver horario
 	4	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	5	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	6	NUÑEZ BURGOS PABLO ANDRES	30	Ver horario
 	7	JONES JOFRE JENNIFER MAKARENA	40	Ver horario
 	8	JONES JOFRE JENNIFER MAKARENA	30	Ver horario
 	9	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
 	10	RIOS GONZALEZ MARIO	30	Ver horario
 	11	RIOS GONZALEZ MARIO	30	Ver horario
 	12	CASTRO GERDES PAULA	30	Ver horario
 	13	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	14	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	15	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	16	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	17	CERIANI LOLAS NICOLL FAVIOLA	30	Ver horario
 	18	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
 	19	BOTAU MANCILLA JORGE EDUARDO	30	Ver horario
 	20	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	21	HECHT CHAU GERNOT	30	Ver horario
 	22	CASTRO GERDES PAULA	30	Ver horario
 	23	RIOS GONZALEZ MARIO	30	Ver horario
 	24	RIOS GONZALEZ MARIO	30	Ver horario
 	25	CASTRO GERDES PAULA	30	Ver horario
 	26	CASTRO GERDES PAULA	30	Ver horario
 	27	NUÑEZ BURGOS PABLO ANDRES	30	Ver horario
 	28	NUÑEZ BURGOS PABLO ANDRES	30	Ver horario
 	29	RIOS GONZALEZ MARIO	30	Ver horario
 	30	RIOS GONZALEZ MARIO	30	Ver horario
 	31	ANDRADE VERGARA BYRON	30	Ver horario
 	32	ANDRADE VERGARA BYRON	30	Ver horario
 	33	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	34	ANDRADE VERGARA BYRON	30	Ver horario
 	35	ANDRADE VERGARA BYRON	30	Ver horario
 	36	ANDRADE VERGARA BYRON	30	Ver horario
 	37	NN	30	Ver horario
 	38	LIRA MENDIGUREN CLAUDIO	30	Ver horario
 	39	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	40	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	41	LOPEZ PEREZ ANTONIO ANDRES	30	Ver horario
 	42	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	43	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	44	RIOS GONZALEZ MARIO	30	Ver horario
 	45	RIOS GONZALEZ MARIO	30	Ver horario
 	46	CASTRO GERDES PAULA	30	Ver horario
 	47	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
 	48	COLLAO MIRANDA LESLIE ROBERTO	30	Ver horario
HAF101	EL MÉTODO CIENTÍFICO	ESTUDIOS HUMANISTICOS	1	VALENCIA ARAYA PEDRO	40	Ver horario
FIS320	ELECTRODINAMICA	FISICA	1	DIB VENTURELLI CLAUDIO	40	Ver horario
 	2	DIB VENTURELLI CLAUDIO	20	Ver horario
ELO108	ELECTRONICA B	ELECTRONICA	1	ROJAS MONRROY CHRISTIAN ALEXIS	45	Ver horario
 	2	PEREZ LEIVA MARCELO ALEJANDRO	45	Ver horario
ELI319	ELECTRONICA DE POTENCIA	INGENIERÍA ELÉCTRICA	1	LEZANA ILLESCA PABLO ANDRES	40	Ver horario
ELI217	ELECTRONICA GENERAL II	INGENIERÍA ELÉCTRICA	1	LEZANA ILLESCA PABLO ANDRES	40	Ver horario
ELI271	ELECTROTECNIA BASICA	INGENIERÍA ELÉCTRICA	1	VARAS BASUALTO ALVARO JAVIER	50	Ver horario
 	2	YURJEVIC PERIN FRANZ MAX	50	Ver horario
 	3	NAVARRETE ALVAREZ JUAN GUILLERMO	50	Ver horario
IWC235	ELEMENTOS DE CORROSION	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	NN	40	Ver horario
IWM280	ELEMENTOS DE MAQUINAS	INGENIERÍA MECÁNICA	1	PERAZZO MAGGI FRANCO ORLANDO	40	Ver horario
ILM152	ELEMENTOS DE MECANICA Y RESISTENCIA DE MAT.	INGENIERÍA MECÁNICA	1	LEIVA DIETZ RODRIGO	60	Ver horario
 	7	PACHECO SANJUAN ALEJANDRO ANDRES	40	Ver horario
MEC258	ELEMENTOS DE MÁQUINAS	INGENIERÍA MECÁNICA	1	PERAZZO MAGGI FRANCO ORLANDO	40	Ver horario
MEC386	ENERGÍA RENOVABLES NO CONVENCIONALES	INGENIERÍA MECÁNICA	1	FLORES MARADIAGA ALEX GEOVANNY	40	Ver horario
CON201	EQUIPOS DE CONSTRUCCION	OBRAS CIVILES	2	SOTO LEMUS MAURICIO ALEJANDRO	73	Ver horario
MEC311	EQUIPOS DE PROCESOS TERMICOS	INGENIERÍA MECÁNICA	1	ROSALES HUERTA CARLOS EDUARDO	60	Ver horario
 	2	ROSALES HUERTA CARLOS EDUARDO	40	Ver horario
MEC378	EQUIPOS Y MÁQUINAS TÉRMICAS	INGENIERÍA MECÁNICA	1	AMADOR DIAZ GERMAN JAVIER	40	Ver horario
HFW124	ESPAÑOL COMO LENGUA EXTRANJERA II	ESTUDIOS HUMANISTICOS	1	CASANUEVA IOMMI MANUEL ANDRES	20	Ver horario
HFW125	ESPAÑOL COMO LENGUA EXTRANJERA III	ESTUDIOS HUMANISTICOS	1	CASANUEVA IOMMI MANUEL ANDRES	20	Ver horario
HFW126	ESPAÑOL COMO LENGUA EXTRANJERA IV	ESTUDIOS HUMANISTICOS	1	CASANUEVA IOMMI MANUEL ANDRES	40	Ver horario
ICS033	ESPIRITU EMPRESARIAL	INGENIERÍA COMERCIAL	1	NN	40	Ver horario
MAT031	ESTADISTICA	MATEMATICA	2	VIDELA JIMENEZ PATRICIO JAVIER	50	Ver horario
 	3	NN	50	Ver horario
 	4	NN	50	Ver horario
INF280	ESTADÍSTICA COMPUTACIONAL	INFORMATICA	1	ALLENDE OLIVARES HECTOR	40	Ver horario
 	2	NARANJO COLLAO RODRIGO ESTEBAN	40	Ver horario
CIV131	ESTATICA DE ESTRUCTURAS	OBRAS CIVILES	1	BAZAEZ GALLARDO RAMIRO ANDRES GABRIE	100	Ver horario
ARQ321	ESTRATEGIAS DE INTERVENCIÓN TERRITORIAL	ARQUITECTURA	1	SOTO CARO MARCELA ANDREA	60	Ver horario
 	2	LEON CANALES JORGE ENRIQUE	40	Ver horario
FIS240	ESTRUCTURA ATOMICA Y NUCLEAR I	FISICA	1	NN	40	Ver horario
FIS241	ESTRUCTURA ATOMICA Y NUCLEAR II	FISICA	1	SCHMIDT ANDRADE IVAN EUGENIO	40	Ver horario
MAT214	ESTRUCTURAS ALGEBRAICAS	MATEMATICA	1	CONTRERAS BARRAZA FABIAN	40	Ver horario
IAO561	ESTRUCTURAS DE ACERO	ARQUITECTURA	1	SCHNAIDT MECKLENBURG CHRISTIAN	50	Ver horario
INF134	ESTRUCTURAS DE DATOS	INFORMATICA	1	HOFFMANN NAGEL HUBERT	50	Ver horario
 	2	HOFFMANN NAGEL HUBERT	50	Ver horario
ELO320	ESTRUCTURAS DE DATOS Y ALGORITMOS	ELECTRONICA	1	AUAT CHEEIN FERNANDO ALFREDO	60	Ver horario
 	2	VOURKAS IOANNIS	60	Ver horario
INF152	ESTRUCTURAS DISCRETAS	INFORMATICA	1	TREIMUN COSTA GERMAN MARCELO	60	Ver horario
 	2	TREIMUN COSTA GERMAN MARCELO	50	Ver horario
CON130	ESTRUCTURAS I	OBRAS CIVILES	1	CARMONA MALATESTA SERGIO	50	Ver horario
MEC151	ESTÁTICA	INGENIERÍA MECÁNICA	1	ROJAS GONZALEZ FERNANDO	55	Ver horario
HRW130	ETICA	ESTUDIOS HUMANISTICOS	1	GARCIA CONTRERAS IVAN ANDRES	40	Ver horario
ICN336	EVALUACION DE PROYECTOS	INDUSTRIAS	1	MOYA ALFARO JOHANA SOLANGE	40	Ver horario
 	2	AMESTICA HERNANDEZ GONZALO DAVID	40	Ver horario
ICN338	EVALUACION DE PROYECTOS GENERALES	INDUSTRIAS	1	MOYA ALFARO JOHANA SOLANGE	40	Ver horario
 	3	DIEZ BENNEWITZ MIGUEL PABLO	40	Ver horario
ICS019	EVALUACION DE PROYECTOS GENERALES	INGENIERÍA COMERCIAL	1	NN	40	Ver horario
 	2	NN	40	Ver horario
IPD420	EVALUACION DE RENDIMIENTO DE SISTEMAS TIC	ELECTRONICA	1	MARTINEZ VERDUGO JOSE MANUEL	20	Ver horario
CIV390	EVALUACIÓN DE PROYECTOS	OBRAS CIVILES	1	BRAVO FORTUNE MARCELO	40	Ver horario
HFW121	EXPRESION ORAL Y ESCRITA	ESTUDIOS HUMANISTICOS	1	CASANUEVA IOMMI MANUEL ANDRES	40	Ver horario
HFW144	EXPRESIÓN ORAL Y ESCRITA	ESTUDIOS HUMANISTICOS	1	BENITEZ VARGAS ALEX IVAN	40	Ver horario
 	2	BENITEZ VARGAS ALEX IVAN	40	Ver horario
 	3	DIAZ TAPIA JULIO GERMAN	40	Ver horario
 	4	DIAZ TAPIA JULIO GERMAN	40	Ver horario
 	5	AVILA ALFARO VIVIANA PATRICIA	40	Ver horario
 	6	AVILA ALFARO VIVIANA PATRICIA	40	Ver horario
ILQ230	FENOMENOS DE TRANSPORTE	INGENIERÍA QUíMICA Y AMBIENTAL	1	JAQUES SOLIS ALONSO VICTOR	40	Ver horario
IPQ430	FENOMENOS TRANSP.AVANZADO (ELEC.)	INGENIERÍA QUíMICA Y AMBIENTAL	1	JAQUES SOLIS ALONSO VICTOR	30	Ver horario
ICN320	FINANZAS	INDUSTRIAS	1	KRISTJANPOLLER RODRIGUEZ WERNER DAVID	40	Ver horario
 	2	GRAFFIGNA BORDIGONI JUAN ERNESTO	40	Ver horario
 	3	CANESSA RICH DIEGO CARLOS	40	Ver horario
ICS014	FINANZAS	INGENIERÍA COMERCIAL	1	PARDO SOTO JAIME ANGEL	40	Ver horario
ICS018	FINANZAS II	INGENIERÍA COMERCIAL	1	GRAFFIGNA BORDIGONI JUAN ERNESTO	40	Ver horario
FIS109	FISICA BASICA I	FISICA	1	CARMONA CAMPOS ROLANDO MANFREDO	35	Ver horario
 	2	ORELLANA GOMEZ CHRISTIAN ANTON	35	Ver horario
 	3	ORELLANA GOMEZ CHRISTIAN ANTON	35	Ver horario
FIS119	FISICA BASICA II	FISICA	1	PEÑA SARABIA JOSE MANUEL	35	Ver horario
 	2	RIOS TORRES RENE ANTONIO	35	Ver horario
FIS129	FISICA BASICA III	FISICA	1	ANDRADE ERMTER SANTIAGO MANUEL	35	Ver horario
 	2	SANCHEZ GUERRERO PAOLA JACKELINE	35	Ver horario
FIS103	FISICA BASICA PARA ARQUITECTOS	FISICA	1	SLUSARENKO STACHNIW VIKTOR	40	Ver horario
FIS205	FISICA COMPUTACIONAL	FISICA	1	FLOREZ URIBE JUAN MANUEL	40	Ver horario
FIS460	FISICA DE PARTICULAS I	FISICA	1	ZERWEKH ARROYO ALFONSO	20	Ver horario
FIS200	FISICA EXPERIMENTAL	FISICA	1	HENRIQUEZ CORREA RICARDO ANDRES	40	Ver horario
 	2	DEL CAMPO SFEIR VALERIA ISABEL	40	Ver horario
FIS110	FISICA GENERAL I	FISICA	1	MORA URRUTIA MARIA LUISA	35	Ver horario
 	2	RAMIREZ CARRASCO FRANCISCA GABRIELA	35	Ver horario
 	3	GARCIA GARCIA CARLOS	35	Ver horario
 	4	SOLIS MIQUIO MIGUEL ANGEL	35	Ver horario
 	5	ALARCON OPAZO HUGO RAUL	35	Ver horario
 	6	DEL CANTO GUTIERREZ PEDRO ENRIQUE	35	Ver horario
 	7	RITZ KOHLER FELIPE ANDRES	35	Ver horario
 	8	NN	35	Ver horario
 	9	SANCHEZ ESPINOZA JAVIERA PATRICIA	40	Ver horario
 	10	SUAREZ MORELL ERIC	35	Ver horario
FIS120	FISICA GENERAL II	FISICA	1	CONTRERAS HIDALGO CARLOS SEBASTIAN	60	Ver horario
 	2	ESPOZ VALLEGA JUAN PEDRO	60	Ver horario
 	3	GONZALEZ FUENTES CLAUDIO ALEJANDRO	60	Ver horario
 	4	ROJAS PEÑA ISAIAS ANTONIO	60	Ver horario
 	5	ARBELAEZ RODRIGUEZ CAROLINA	40	Ver horario
 	6	FLOREZ URIBE JUAN MANUEL	60	Ver horario
 	7	FLOREZ URIBE JUAN MANUEL	35	Ver horario
 	8	CORRALES ITURRIAGA TOMAS PATRICIO	35	Ver horario
 	9	ACEVEDO GUTIERREZ CRISTIAN ANDRES	35	Ver horario
 	10	BRAVO CASTILLO SERGIO JAVIER	35	Ver horario
 	11	MORA URRUTIA MARIA LUISA	35	Ver horario
 	12	AYALA NUÑEZ CESAR ALEJANDRO	35	Ver horario
 	13	PARRA GONZALEZ CAROLINA	35	Ver horario
FIS130	FISICA GENERAL III	FISICA	1	VALDES LEYTON JORGE EDUARDO	60	Ver horario
 	2	ESPOZ VALLEGA JUAN PEDRO	60	Ver horario
 	3	CVETIC - GORAZD	60	Ver horario
 	4	ARAVENA ORTEGA OSCAR ANDRES	60	Ver horario
 	5	ARRIETA BUSTAMANTE GUILLERMO GUST	60	Ver horario
FIS140	FISICA GENERAL IV	FISICA	1	IBAÑEZ RODRIGUEZ WLADIMIR	60	Ver horario
 	2	ECHIBURU FUENZALIDA MAURICIO ANDRES	60	Ver horario
 	3	ROJAS PEÑA ISAIAS ANTONIO	60	Ver horario
 	4	ZERWEKH ARROYO ALFONSO	60	Ver horario
 	5	ARRIETA BUSTAMANTE GUILLERMO GUST	60	Ver horario
QUI244	FISICOQUIMICA III	QUIMICA	1	FRYDEL . DARIUSZ DEREK	40	Ver horario
ICQ327	FLOTACION	INGENIERÍA QUíMICA Y AMBIENTAL	1	YIANATOS BERNARDINO JUAN	40	Ver horario
HRW131	FORMAC.Y LIDERAZGO EMPRESARIAL	ESTUDIOS HUMANISTICOS	1	VALLE SANGUINETTI CARLA ROSSINA	40	Ver horario
 	2	MUCIENTES ARELLANO GLORIA DEL CARMEN	40	Ver horario
 	3	MUCIENTES ARELLANO GLORIA DEL CARMEN	40	Ver horario
 	4	VALLE SANGUINETTI CARLA ROSSINA	40	Ver horario
 	5	HONORATO FALCON XIMENA MARIA	40	Ver horario
ILI281	FUND. DE INV. DE OPERACIONES	INFORMATICA	1	GOMEZ SANCHEZ MARIAM	70	Ver horario
ILM271	FUNDAMENTOS DE CALIDAD	INGENIERÍA MECÁNICA	1	SARIEGO PASTEN PEDRO MARCO	40	Ver horario
MEC280	FUNDAMENTOS DE CALIDAD	INGENIERÍA MECÁNICA	1	SARIEGO PASTEN PEDRO MARCO	40	Ver horario
IWQ350	FUNDAMENTOS DE CONTROL INDUSTRIAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	BERGH OLIVARES LUIS GUILLERMO	50	Ver horario
ILM286	FUNDAMENTOS DE DISEÑO	INGENIERÍA MECÁNICA	1	MENDOZA RAMOS JORGE FERN	40	Ver horario
ILD208	FUNDAMENTOS DE ELECTRONICA	ELECTRONICA	1	MARIN GONZALEZ GUSTAVO	40	Ver horario
ELI270	FUNDAMENTOS DE ELECTROTECNIA	INGENIERÍA ELÉCTRICA	1	VARAS BASUALTO ALVARO JAVIER	40	Ver horario
 	2	VARAS BASUALTO ALVARO JAVIER	40	Ver horario
IWQ250	FUNDAMENTOS DE INGENIERIA BIOQUIMICA	INGENIERÍA QUíMICA Y AMBIENTAL	1	ALMONACID MERINO SERGIO FELIPE	60	Ver horario
ILQ109	FUNDAMENTOS DE TERMODINAMICA	INGENIERÍA QUíMICA Y AMBIENTAL	1	RAMIREZ LIVINGSTON ALBERTO	40	Ver horario
TEL222	FUNDAMENTOS DE TRANSMISIÓN DE SEÑALES	ELECTRONICA	1	OLIVARES VELIZ RICARDO	50	Ver horario
MET350	FUNDAMENTOS DE TRIBOLOGÍA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	NN	40	Ver horario
MEC245	FUNDAMENTOS DEL DISEÑO	INGENIERÍA MECÁNICA	1	MENDOZA RAMOS JORGE FERN	40	Ver horario
EFI105	FÚTBOL	DEFIDER	1	SORIANO BARQUIN JORGE CRISTIAN	30	Ver horario
 	2	SORIANO BARQUIN JORGE CRISTIAN	30	Ver horario
 	3	SORIANO BARQUIN JORGE CRISTIAN	30	Ver horario
 	4	SORIANO BARQUIN JORGE CRISTIAN	30	Ver horario
FIS300	Física Experimental	FISICA	1		20	Ver horario
FIS461	Física de Partículas II	FISICA	1	SIDDIKOV . MARAT	20	Ver horario
CIV205	GEOLOGÍA	OBRAS CIVILES	1	GARRIDO CARVAJAL, LIVIO	75	Ver horario
CON100	GEOMETRIA DESCRIPTIVA	OBRAS CIVILES	1	SANCHEZ DROGUETT EDUARDO GONZALO	49	Ver horario
ARQ241	GEOMETRÍA ARQUITECTÓNICA	ARQUITECTURA	1	SILVA GOPFERT PABLO ANDRES	40	Ver horario
 	2	BASTIAS GOMEZ FREDDY ANTONIO	40	Ver horario
IMQ350	GESTION AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	GARCIA GEN SANTIAGO	40	Ver horario
IWM320	GESTION AMBIENTAL	INGENIERÍA MECÁNICA	2	VEGA NUÑEZ CRISTIAN ANDRES	50	Ver horario
ICN346	GESTION CALIDAD TOTAL	INDUSTRIAS	1	LOPEZ CAMPOS MONICA ALEJANDRA	40	Ver horario
 	2	YAÑEZ SANDIVARI LUIS	40	Ver horario
ICN376	GESTION DE ACTIVOS Y NEGOCIOS MINEROS	INDUSTRIAS	1	OPORTUS ROMERO PATRICIO ARNOLDO	40	Ver horario
ICN256	GESTION DE INVERSIONES	INDUSTRIAS	1	KRISTJANPOLLER RODRIGUEZ WERNER DAVID	40	Ver horario
ICS010	GESTION DE INVESTIGACION DE OPERACIONES	INGENIERÍA COMERCIAL	1	VILLALOBOS TORRES HUMBERTO MARCELO	40	Ver horario
ILN250	GESTION DE INVESTIGACION DE OPERACIONES	INDUSTRIAS	1	YURASZECK ESPINOZA FRANCISCO JAVIER	40	Ver horario
 	3	SILVA GONZALEZ MAGDA C	40	Ver horario
 	4	ESCALONA RODRIGUEZ PABLO	40	Ver horario
 	5	FAVEREAU URQUIZA RAFAEL ALEJ	40	Ver horario
 	7	FAVEREAU URQUIZA RAFAEL ALEJ	40	Ver horario
ICN343	GESTION DE OPERACIONES	INDUSTRIAS	1	KRISTJANPOLLER RODRIGUEZ FREDY ARIEL	40	Ver horario
 	2	STEGMAIER BRAVO RAUL	40	Ver horario
ICS020	GESTION DE OPERACIONES	INGENIERÍA COMERCIAL	1	NN	40	Ver horario
ICN344	GESTION DE OPERACIONES II	INDUSTRIAS	1	ESCALONA RODRIGUEZ PABLO	40	Ver horario
 	2	LOPEZ CAMPOS MONICA ALEJANDRA	40	Ver horario
ICN322	GESTION ESTRATEGICA	INDUSTRIAS	1	SAAVEDRA RODRIGUEZ OSCAR JULIO	40	Ver horario
 	2	YAÑEZ MARTINEZ DIEGO IGNACIO	40	Ver horario
ICS022	GESTION ESTRATEGICA	INGENIERÍA COMERCIAL	1	CHAVEZ VELASQUEZ HARDY OMAR	40	Ver horario
ICS028	GESTION ESTRATEGICA II	INGENIERÍA COMERCIAL	1	NARANJO TAPIA ALBERTO	40	Ver horario
ICS027	GESTIÓN DE CALIDAD TOTAL	INGENIERÍA COMERCIAL	1	ORTUZAR MATURANA RODRIGO IVAN	40	Ver horario
CIV381	GESTIÓN DE LA CALIDAD TOTAL EN LA CADENA DE SUMINISTRO	OBRAS CIVILES	1	NN	60	Ver horario
ICN296	GESTIÓN DE PERSONAS Y HABILIDADES DIRECTIVAS	INDUSTRIAS	1	DE LA FUENTE MUÑOZ FRANCISCO JAVIER	40	Ver horario
INF360	GESTIÓN DE PROYECTOS INFORMÁTICOS	INFORMATICA	1	HEVIA RODRIGUEZ LUIS	50	Ver horario
ILN221	GESTIÓN ENERGÉTICA I	INDUSTRIAS	1	DEMARCO BULL RODRIGO ANDRES	40	Ver horario
 	2	DEMARCO BULL RODRIGO ANDRES	40	Ver horario
ILN222	GESTIÓN ENERGÉTICA II	INDUSTRIAS	1	FUENTES CASTILLO ANDRES HERNAN	40	Ver horario
 	2	FUENTES CASTILLO ANDRES HERNAN	40	Ver horario
ICS859	GESTIÓN ESTRATÉGICA Y VENTAJA COMPETITIVA: LA PERSPECTIVA CHILENA	INGENIERÍA COMERCIAL	1	CEA VALENCIA JORGE MAURICIO	40	Ver horario
ARQ521	GESTIÓN TERRITORIAL	ARQUITECTURA	1	SAAVEDRA DE MATEO JOAN RODRIGO	40	Ver horario
EFI106	GIMNASIA AERÓBICA	DEFIDER	1	CERIANI LOLAS NICOLL FAVIOLA	30	Ver horario
 	2	CERIANI LOLAS NICOLL FAVIOLA	30	Ver horario
 	3	CERIANI LOLAS NICOLL FAVIOLA	30	Ver horario
EFI107	GIMNASIA ARTÍSTICA	DEFIDER	1	IBACACHE CALDERON PATRICIA MACARENA	40	Ver horario
IDP200	GRAFICA DE PRODUCTOS	Ingeniería en Diseño	1	BRIEDE WESTERMEYER JUAN CARLOS	40	Ver horario
IWM187	GRAFICA DE SISTEMAS MECANICOS	INGENIERÍA MECÁNICA	1	CUEVAS ARAVENA JULIA IVONNE	60	Ver horario
IWM185	GRAFICA EN INGENIERIA	INGENIERÍA MECÁNICA	1	MUÑOZ CONTRERAS SERGIO ANTONIO	40	Ver horario
 	5	JOFRE MONTANER HELENA LILY	40	Ver horario
IWM186	GRAFICA EN INGENIERIA MECANICA	INGENIERÍA MECÁNICA	1	RHEINSCHMIDT . UDO RUDOLF	40	Ver horario
MEC142	GRÁFICA DE SISTEMAS MECÁNICOS	INGENIERÍA MECÁNICA	1	RHEINSCHMIDT . UDO RUDOLF	40	Ver horario
 	2	CUEVAS ARAVENA JULIA IVONNE	40	Ver horario
MEC141	GRÁFICA EN INGENIERÍA MECÁNICA	INGENIERÍA MECÁNICA	1	RHEINSCHMIDT . UDO RUDOLF	40	Ver horario
ARQ412	HABITAR LA LUZ	ARQUITECTURA	1	GLARIA KAHNI AMAYA	40	Ver horario
EFI108	HANDBOL	DEFIDER	1	NUÑEZ BURGOS PABLO ANDRES	30	Ver horario
 	2	NUÑEZ BURGOS PABLO ANDRES	30	Ver horario
CIV346	HIDRAULICA APLICADA	OBRAS CIVILES	1	KAMANN CHACANA PEDRO GASPAR	70	Ver horario
CIV242	HIDRAULICA TEORICA Y LABORATORIO	OBRAS CIVILES	1	FLORES AUDIBERT RAUL PEDRO	75	Ver horario
IPO446	HIDRODINÁMICA COSTERA	OBRAS CIVILES	1	CATALAN MONDACA PATRICIO ANDRES	20	Ver horario
MET237	HIDROMETALURGIA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	IBAÑEZ RIVERA JUAN PATRICIO	40	Ver horario
HFW131	HISTORIA CHILENA CONTEMPORANEA	ESTUDIOS HUMANISTICOS	1	BARRIA SLAKO ARMANDO OSCAR	40	Ver horario
 	2	BARRIA SLAKO ARMANDO OSCAR	40	Ver horario
HRW203	HISTORIA DE LA CONSTRUCCION	ESTUDIOS HUMANISTICOS	1	AYALA VELOSO JUAN GONZALO	40	Ver horario
HRW164	HISTORIA DEL PENSAMIENTO CIENTIFICO	ESTUDIOS HUMANISTICOS	1	IOMMI AMUNATEGUI XIMENA	40	Ver horario
HAH101	HISTORIA ECONÓMICA	ESTUDIOS HUMANISTICOS	1	BARRIA SLAKO ARMANDO OSCAR	40	Ver horario
 	2	BARRIA SLAKO ARMANDO OSCAR	40	Ver horario
 	3	ARACENA HREPIC FELIPE	40	Ver horario
 	4	ARACENA HREPIC FELIPE	40	Ver horario
HFW134	HISTORIA RECIENTE DE CHILE: POLÍTICA, DERECHOS HUM	ESTUDIOS HUMANISTICOS	1	CHATEAU CANTILLANA PIERRE FRANCISCO	20	Ver horario
CIV331	HORMIGÓN ARMADO	OBRAS CIVILES	1	LEIVA HENRIQUEZ GILBERTO	100	Ver horario
HFW137	IDENTIDAD CHILENA	ESTUDIOS HUMANISTICOS	1	CASANUEVA IOMMI MANUEL ANDRES	20	Ver horario
ICIPEV	IND.VESPERTINO	INDUSTRIAS	1	NN	0	Ver horario
 	2		0	Ver horario
 	3	NN	0	Ver horario
 	4		0	Ver horario
 	5		0	Ver horario
 	6	NN	0	Ver horario
 	7		0	Ver horario
IWQ240	INDUSTRIA QUIMICA CHILENA	INGENIERÍA QUíMICA Y AMBIENTAL	201	CARVAJAL DEL VILLAR HUMBERTO	40	Ver horario
IWN270	INFORMACION Y CONTROL FINANCIERO	INDUSTRIAS	1	FIGUEROA SILVA VICTOR	40	Ver horario
 	2	MARIN GONZALEZ MANUEL ENRIQUE	40	Ver horario
 	3	ALVAREZ NUÑEZ RAMON ALBERTO	40	Ver horario
 	4	ALVAREZ NUÑEZ RAMON ALBERTO	40	Ver horario
 	6	MARIN GONZALEZ MANUEL ENRIQUE	40	Ver horario
 	7	STEFFENS VILLALON PATRICIO	40	Ver horario
 	8	STEFFENS VILLALON PATRICIO	40	Ver horario
ICN270	INFORMACIÓN Y MATEMÁTICA FINANCIERA	INDUSTRIAS	1	MARIN GONZALEZ MANUEL ENRIQUE	40	Ver horario
INF155	INFORMÁTICA TEÓRICA	INFORMATICA	1	VON BRAND SKOPNIK HORST	60	Ver horario
ICN342	INGENIERIA DE PLANTAS INDUSTRIALES	INDUSTRIAS	1	STEGMAIER BRAVO RAUL	40	Ver horario
 	2	KRISTJANPOLLER RODRIGUEZ FREDY ARIEL	40	Ver horario
 	3	GOMEZ MUÑOZ SIMON MATHIAS	40	Ver horario
IMM381	INGENIERIA DEL DISEÑO MECANICO	INGENIERÍA MECÁNICA	1	SARIEGO PASTEN PEDRO MARCO	40	Ver horario
CIV378	INGENIERIA DEL MEDIO AMBIENTE	OBRAS CIVILES	1	RUBIO ROMERO PATRICIO	70	Ver horario
ILN230	INGENIERIA ECONOMICA	INDUSTRIAS	1	MICHELL VALENCIA KEVIN ESTEBAN	40	Ver horario
 	2	MARCHANT GARCIA JAIME	40	Ver horario
 	3	DIEZ BENNEWITZ MIGUEL PABLO	40	Ver horario
 	4	DIEZ BENNEWITZ MIGUEL PABLO	40	Ver horario
CON241	INGENIERIA HIDRAULICA	OBRAS CIVILES	1	FLORES AUDIBERT RAUL PEDRO	60	Ver horario
CIV338	INGENIERIA SISMICA	OBRAS CIVILES	1	AGUIRRE AHUMADA CARLOS	90	Ver horario
CIV368	INGENIERIA VIAL	OBRAS CIVILES	1	WAHR DANIEL CARLOS	60	Ver horario
IQA264	INGENIERÍA AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	LAZO ACUÑA ANDREA PAOLA	60	Ver horario
ICVESP	INGENIERÍA COMERCIAL PROGRAMA VESPERTINO	INGENIERÍA COMERCIAL	1		0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
 	4		0	Ver horario
 	5		0	Ver horario
INF225	INGENIERÍA DE SOFTWARE	INFORMATICA	1	BEROIZA OSSES FELIPE IGNACIO	50	Ver horario
 	2	ORMAZABAL ORELLANA WLADIMIR ELIAS	50	Ver horario
INF276	INGENIERÍA, INFORMÁTICA Y SOCIEDAD	INFORMATICA	1	CONTRERAS VELIZ JOSE LINO	40	Ver horario
HCW100	INGLÉS 1	ESTUDIOS HUMANISTICOS	1	SAFATLE MEDIC YURIEE EDITH	20	Ver horario
 	2	SAFATLE MEDIC YURIEE EDITH	20	Ver horario
 	3	DIAZ PARRA LUIS ANTONIO	20	Ver horario
 	4	DIAZ PARRA LUIS ANTONIO	20	Ver horario
 	5	HENRIQUEZ NUÑEZ GUILLERMO	20	Ver horario
 	6	TOLEDO VERGARA ROSA ELISA	20	Ver horario
HCW101	INGLÉS 2	ESTUDIOS HUMANISTICOS	1	HIDALGO BECERRA ALEJANDRA ANDREA	20	Ver horario
 	2	HIDALGO BECERRA ALEJANDRA ANDREA	20	Ver horario
 	3	HIDALGO BECERRA ALEJANDRA ANDREA	20	Ver horario
 	4	HIDALGO BECERRA ALEJANDRA ANDREA	20	Ver horario
 	5	HIDALGO BECERRA ALEJANDRA ANDREA	20	Ver horario
 	6	HENRIQUEZ NUÑEZ GUILLERMO	20	Ver horario
HCW102	INGLÉS 3	ESTUDIOS HUMANISTICOS	1	VACCARO LEIVA MARISEL ELIANA	20	Ver horario
 	2	VACCARO LEIVA MARISEL ELIANA	20	Ver horario
 	3	VACCARO LEIVA MARISEL ELIANA	20	Ver horario
 	4	VACCARO LEIVA MARISEL ELIANA	20	Ver horario
 	5	DIAZ PARRA LUIS ANTONIO	20	Ver horario
 	6	TOLEDO VERGARA ROSA ELISA	20	Ver horario
HCW200	INGLÉS 4	ESTUDIOS HUMANISTICOS	1	LOPEZ LOPEZ CAROL PAMELA	20	Ver horario
 	2	LOPEZ LOPEZ CAROL PAMELA	20	Ver horario
 	3	LOPEZ LOPEZ CAROL PAMELA	20	Ver horario
 	5	LOPEZ LOPEZ CAROL PAMELA	20	Ver horario
 	6	TOLEDO VERGARA ROSA ELISA	20	Ver horario
HCW201	INGLÉS 5	ESTUDIOS HUMANISTICOS	1	VERA SAAVEDRA JIMMY SEBASTIAN	20	Ver horario
 	2	VERA SAAVEDRA JIMMY SEBASTIAN	20	Ver horario
 	3	VERA SAAVEDRA JIMMY SEBASTIAN	20	Ver horario
 	4	VERA SAAVEDRA JIMMY SEBASTIAN	20	Ver horario
 	5	SESSAREGO ESPELETA IDA	20	Ver horario
 	6	TOLEDO VERGARA ROSA ELISA	20	Ver horario
HCW202	INGLÉS 6	ESTUDIOS HUMANISTICOS	1	OYANEDEL GONZALEZ MARIANNA GINEVA	20	Ver horario
 	2	OYANEDEL GONZALEZ MARIANNA GINEVA	20	Ver horario
 	3	SESSAREGO ESPELETA IDA	20	Ver horario
 	4	DIAZ PARRA LUIS ANTONIO	20	Ver horario
 	5	TOLEDO VERGARA ROSA ELISA	20	Ver horario
TEL101	INICIACIÓN A LA PROGRAMACIÓN	ELECTRONICA	1	OLIVARES RONCAGLIOLO PATRICIO ANDRES	40	Ver horario
 	2	ZUÑIGA BARRAZA MARCOS DAVID	40	Ver horario
ICM316	INST.Y ECON.PLANTAS DE FUERZA	INGENIERÍA MECÁNICA	1	MENDOZA RAMOS JORGE FERN	40	Ver horario
ARQ441	INSTALACIONES ELÉCTRICAS, SANITARIAS Y CLIMA	ARQUITECTURA	1	GALVEZ HUERTA MIGUEL ANGEL	60	Ver horario
CON224	INSTALACIONES EN EDIFICACIONES	OBRAS CIVILES	1	SOLAR MARDONEZ RODRIGO OCTAVIO	50	Ver horario
INF295	INTELIGENCIA ARTIFICIAL	INFORMATICA	1	ROJAS GONZALEZ NICOLAS FERNANDO	40	Ver horario
INF388	INTELIGENCIA ARTIFICIAL AVANZADA	INFORMATICA	1	RIFF ROJAS MARIA CRISTINA	40	Ver horario
FIS280	INTRODUCCION A LA ASTROFISICA	FISICA	1	NN	40	Ver horario
ELI110	INTRODUCCION A LA ELECTROTECNIA	INGENIERÍA ELÉCTRICA	1	RIOS VIELMA JAVIER IGNACIO	40	Ver horario
FIS100	INTRODUCCION A LA FISICA	FISICA	1	NN	30	Ver horario
 	2	NN	30	Ver horario
 	3	GONZALEZ INOSTROZA ALEJANDRO ROBERTO	30	Ver horario
 	4	NN	30	Ver horario
 	5	ROCO ZUÑIGA ROBERTO CARLOS	30	Ver horario
 	6	NUÑEZ RAMIREZ CESAR DANIEL	30	Ver horario
 	7	NN	30	Ver horario
 	8	NN	30	Ver horario
 	9	ORTIZ COLLAO SEBASTIAN ELIAS	30	Ver horario
 	10	ALLENDES FLORES CRISTIAN ANDRES	30	Ver horario
 	11	OLAVARRIA ULLOA GONZALO ANDRES	30	Ver horario
 	12	ERRAZ LEVAGGI DANIEL ANDRES	30	Ver horario
 	13	NN	30	Ver horario
 	14	VALDES GUAJARDO RODRIGO	30	Ver horario
 	15	CARMONA CAMPOS ROLANDO MANFREDO	30	Ver horario
 	16	VERGARA ROJAS RODRIGO ALONSO	30	Ver horario
 	17	PULGAR SOTO GUSTADO ANDRES	30	Ver horario
 	18	BARRIOS TUBINO DANIELA DEL CARMEN	30	Ver horario
 	19	VALDES GUAJARDO RODRIGO	30	Ver horario
 	20	CAVIEDES BALEISAN MAURICIO ANDRES	30	Ver horario
 	22	ROCO ZUÑIGA ROBERTO CARLOS	30	Ver horario
 	23	FIGUEROA ESCALIER CLAUDIO EMILIO	30	Ver horario
 	24	MERY DUARTE MARIO FELIPE	30	Ver horario
 	25	VIGNATTI MUÑOZ JONATHAN	30	Ver horario
 	26	ROMANQUE ALBORNOZ CRISTIÁN ALBERTO	30	Ver horario
 	27	SANCHEZ GUERRERO PAOLA JACKELINE	30	Ver horario
 	28	ORTIZ COLLAO SEBASTIAN ELIAS	30	Ver horario
 	29	NN	30	Ver horario
 	30	PERASSO ADUNCE JOHANNA ANTONIA	30	Ver horario
 	31	FIGUEROA ESCALIER CLAUDIO EMILIO	30	Ver horario
 	32	SANCHEZ GUERRERO PAOLA JACKELINE	30	Ver horario
 	33	VALLS ALMIRALL JAIME JOSE	30	Ver horario
 	35	NN	30	Ver horario
 	36	NN	30	Ver horario
 	37	ALLENDES SUAREZ PEDRO	30	Ver horario
 	38	DEL CANTO GUTIERREZ PEDRO ENRIQUE	30	Ver horario
 	39	ROCO ZUÑIGA ROBERTO CARLOS	40	Ver horario
 	40	NN	40	Ver horario
 	41	NEGRETE SARRAF OSCAR ANDRES	30	Ver horario
FIS250	INTRODUCCION A LA FISICA DE SOLIDOS	FISICA	1	PACHECO DOLL MONICA JEANETTE	50	Ver horario
IWG100	INTRODUCCION A LA INGENIERIA	DIRECCION GRAL. DOCENCIA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	3	NN	0	Ver horario
 	4	NN	0	Ver horario
 	5	NN	0	Ver horario
 	6	NN	0	Ver horario
 	7	NN	0	Ver horario
 	8	NN	0	Ver horario
 	9	NN	0	Ver horario
 	10	NN	0	Ver horario
IWG101	INTRODUCCION A LA INGENIERIA	DIRECCION GRAL. DOCENCIA	1	BRAVO FORTUNE MARCELO	76	Ver horario
 	2	MORA AGUIRRE CELIN	40	Ver horario
 	3	NORAMBUENA VALDIVIA MARGARITA ANDREA	60	Ver horario
 	4	MICHELL VALENCIA KEVIN ESTEBAN	40	Ver horario
 	5	SIMPSON RIVERA RICARDO JOSE	69	Ver horario
 	6	SANCHEZ DROGUETT EDUARDO GONZALO	42	Ver horario
 	7	KOURO RENAER SAMIR FELIPE	50	Ver horario
 	8	AMESTICA HERNANDEZ GONZALO DAVID	40	Ver horario
 	9	CREIXELL FUENTES WERNER UWE	60	Ver horario
 	10	GUERRERO SALDES LORNA ELENA	60	Ver horario
 	11	DOROCHESI FERNANDOIS MARIO	40	Ver horario
 	12	MORA AGUIRRE CELIN	41	Ver horario
 	13	CABRERA CONTRERAS MANUEL	65	Ver horario
 	14	MORA AGUIRRE CELIN	40	Ver horario
 	15	MORA AGUIRRE CELIN	40	Ver horario
 	16	SALAZAR ALBORNOZ RODOLFO IGNACIO	40	Ver horario
 	17	ERRAZ LEVAGGI DANIEL ANDRES	40	Ver horario
 	18	KOURO RENAER SAMIR FELIPE	51	Ver horario
 	19	GOMEZ MUÑOZ SIMON MATHIAS	40	Ver horario
 	50	MORA AGUIRRE CELIN	50	Ver horario
HTW130	INTRODUCCION A LA MUSICA	ESTUDIOS HUMANISTICOS	1	OLATE VALENZUELA SILVIO RENATO	40	Ver horario
FIS265	INTRODUCCIÓN A LA BIOFÍSICA	FISICA	1	CORRALES ITURRIAGA TOMAS PATRICIO	40	Ver horario
AST100	INTRODUCCIÓN A LA ASTROFÍSICA	FISICA	1	QUITRAL MANOSALVA PAOLA ANGELICA	40	Ver horario
INF396	INTRODUCCIÓN A LA CIENCIA DE DATOS	INFORMATICA	1	ALLENDE CID HECTOR GABRIEL	40	Ver horario
ICS161	INTRODUCCIÓN A LA ECONOMÍA	INGENIERÍA COMERCIAL	1	CASTRO LANDMAN RUBEN ESTANISL	40	Ver horario
 	2	MUÑOZ URTUBIA NESTOR ANDRES	40	Ver horario
 	3	MUÑOZ URTUBIA NESTOR ANDRES	40	Ver horario
 	4	GATICA SILVA MACARENA	40	Ver horario
 	5	CASTRO LANDMAN RUBEN ESTANISL	40	Ver horario
FIS104	INTRODUCCIÓN A LA FÍSICA CONTEMPORÁNEA	FISICA	1	DIB VENTURELLI CLAUDIO	40	Ver horario
ICN367	INTRODUCCIÓN A LA GESTIÓN DE PROYECTOS ENERGÉTICOS	INDUSTRIAS	1	NN	40	Ver horario
MEC101	INTRODUCCIÓN A LA INGENIERÍA MECÁNICA	INGENIERÍA MECÁNICA	1	SARIEGO PASTEN PEDRO MARCO	40	Ver horario
 	2	VALDENEGRO OYANEDER RENE ANTONIO	40	Ver horario
IQA161	INTRODUCCIÓN A LA INGENIERÍA SOSTENIBLE	INGENIERÍA QUíMICA Y AMBIENTAL	1	NN	40	Ver horario
ICS869	INTRODUCCIÓN A LA INNOVACIÓN SOCIAL	INGENIERÍA COMERCIAL	1	GUERRA GENSKOWSKY LAUTARO	40	Ver horario
FIS266	INTRODUCCIÓN A LOS NANOBIOMATERIALES	FISICA	1	PARRA GONZALEZ CAROLINA	40	Ver horario
MAT070	INTRODUCCIÓN AL CÁLCULO	MATEMATICA	1	PEREZ OJEDA JAVIER IGNACIO	40	Ver horario
 	1	FIGUEROA REBOLLEDO GLADYS	40	Ver horario
 	2	JIMENEZ HUGHES JUAN ENRIQUE	40	Ver horario
 	2	VIDAL OLIVERO ALEJANDRO ANDRES	40	Ver horario
 	3	VIDAL OLIVERO ALEJANDRO ANDRES	40	Ver horario
 	3	LOPEZ CEPEDA PATRICIA	40	Ver horario
 	4	CABRERA BIANCHETTI ALDO ANTONIO	40	Ver horario
 	4	ORTIZ COLLAO SEBASTIAN ELIAS	40	Ver horario
 	5	CALDERON CESPEDES ALFREDO EDUARDO	40	Ver horario
 	5	TAPIA CARO JOSE ANDRES	40	Ver horario
 	6	NN	40	Ver horario
 	6	BARRIENTOS DIAZ SERGIO LUIS	40	Ver horario
 	7	OGUEDA OLIVA ALONSO GABRIEL	40	Ver horario
 	7	NN	40	Ver horario
ARQ418	INTRODUCCIÓN ARQUITECTURA EXTREMA	ARQUITECTURA	1	SERRANO RODRIGUEZ PEDRO ROLANDO	40	Ver horario
IDP301	INVESTIGACION APLICADA	Ingeniería en Diseño	1	VIVEROS BAEZ RICARDO JOSE	40	Ver horario
ICM392	INVESTIGACION APLICADA II	INGENIERÍA MECÁNICA	1	PEREZ POZO LUIS CARLOS	10	Ver horario
 	2	FLORES MARADIAGA ALEX GEOVANNY	10	Ver horario
 	3	VALDENEGRO OYANEDER RENE ANTONIO	10	Ver horario
 	4	ROJAS GONZALEZ FERNANDO	10	Ver horario
 	5	AMADOR DIAZ GERMAN JAVIER	10	Ver horario
 	6	COOPER VILLAGRAN CHRISTOPHER	10	Ver horario
 	7	MENA YANSSEN RAFAEL	10	Ver horario
 	8	ESPINOZA SILVA JAIME	10	Ver horario
 	9	SARIEGO PASTEN PEDRO MARCO	10	Ver horario
 	10	ROSALES HUERTA CARLOS EDUARDO	10	Ver horario
 	11	BARRAZA VICENCIO RODRIGO SEBASTI	10	Ver horario
 	12	PACHECO SANJUAN ALEJANDRO ANDRES	10	Ver horario
 	13	PERAZZO MAGGI FRANCO ORLANDO	10	Ver horario
 	14	TOLEDO TORRES MARIO GONZALO	10	Ver horario
 	15	NIKULIN CHANDIA CHRISTOPHER	10	Ver horario
 	16	RHEINSCHMIDT . UDO RUDOLF	10	Ver horario
 	17	OLGUIN ASTUDILLO HERNAN ANDRES	10	Ver horario
INF293	INVESTIGACIÓN DE OPERACIONES	INFORMATICA	1	RIFF ROJAS MARIA CRISTINA	60	Ver horario
EFI109	JUDO	DEFIDER	1	VERGARA VERDEJO GASTON LUIS	40	Ver horario
ICS031	JUEGO DE NEGOCIOS	INGENIERÍA COMERCIAL	1	ZURITA ROMAN IVAN	40	Ver horario
EFI110	KÁRATE	DEFIDER	1	NUÑEZ SOTO SERGIO OCTAVIO	40	Ver horario
 	2	NUÑEZ SOTO SERGIO OCTAVIO	30	Ver horario
QUI217	LAB. DE QUIMICA INORGANICA II	QUIMICA	1	THOMET ISLA FRANZ ANDRES	40	Ver horario
LAB102	LAB. FIS.BASICA II	FISICA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	3	NN	0	Ver horario
 	4	NN	0	Ver horario
 	5	NN	0	Ver horario
LAB101	LAB. FISICA BASICA I	FISICA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	4	NN	0	Ver horario
LAB110	LAB. FISICA GENERAL I	FISICA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	3	NN	0	Ver horario
 	4	NN	0	Ver horario
QUI137	LAB. QUIMICA ORGANICA I	QUIMICA	1	OSORIO OLIVARES MAURICIO ENRIQUE	40	Ver horario
ELO212	LAB. SISTEMAS DIGITALES	ELECTRONICA	1	SOLIS HERNANDEZ MAURICIO ANDRES	27	Ver horario
 	2	CARVAJAL BARRERA GONZALO ANDRES	27	Ver horario
 	3	ALVIÑA OLAVARRIA ALEJANDRO	27	Ver horario
ELI329	LAB.DE ACCIONAMIENTOS ELECTRICOS	INGENIERÍA ELÉCTRICA	1	JULIET AVILES JORGE ANDRES	40	Ver horario
ELO324	LAB.DE REDES DE COMPUTADORES Y SIST.OPERATIV	ELECTRONICA	1	MALONNEK WETZEL RUDY SERGIO	24	Ver horario
LAB120	LAB.FIS.GRAL.II	FISICA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	3	NN	0	Ver horario
 	4	NN	0	Ver horario
 	5	NN	0	Ver horario
LAB130	LAB.FIS.GRAL.III	FISICA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	3	NN	0	Ver horario
 	4	NN	0	Ver horario
 	5	NN	0	Ver horario
 	6	NN	0	Ver horario
LAB140	LAB.FIS.GRAL.IV	FISICA	1	NN	0	Ver horario
 	2	NN	0	Ver horario
 	3	NN	0	Ver horario
 	4	NN	0	Ver horario
 	5	NN	0	Ver horario
 	6	NN	1	Ver horario
 	7	NN	0	Ver horario
 	8	NN	0	Ver horario
 	9	NN	0	Ver horario
 	10	NN	0	Ver horario
ELI325	LABORATORIO DE ACCIONAMIENTOS ELECTRIC.B	INGENIERÍA ELÉCTRICA	1	PORZIO LOPEZ ALEJANDRO	40	Ver horario
ELI359	LABORATORIO DE ALTA TENSION A	INGENIERÍA ELÉCTRICA	1	SCHURCH BRANDT ROGER STEFFAN	20	Ver horario
ELO241	LABORATORIO DE COMUNICACIONES	ELECTRONICA	1	GUICHARROUSSE VARGAS PATRICK FRANCOIS	18	Ver horario
 	2	GUICHARROUSSE VARGAS PATRICK FRANCOIS	18	Ver horario
 	3	GUICHARROUSSE VARGAS PATRICK FRANCOIS	18	Ver horario
ELO271	LABORATORIO DE CONTROL AUTOMATICO	ELECTRONICA	2	AGÜERO VÁSQUEZ JUAN CARLOS	15	Ver horario
ELO382	LABORATORIO DE ELECTRONICA INDUSTRIAL	ELECTRONICA	1	PEREZ LEIVA MARCELO ALEJANDRO	16	Ver horario
 	2	LLOR CARRASCO ANA MARIA	16	Ver horario
TEL132	LABORATORIO DE ELECTRÓNICA DIGITAL	ELECTRONICA	1	AHMED ABDELHAMID MOHAMED ABDELHAMID	40	Ver horario
QUI243	LABORATORIO DE FISICOQUIMICA	QUIMICA	1	PINTER . BALAZS	40	Ver horario
MET308	LABORATORIO DE INGENIERÍA METALÚRGICA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	CASAS DE PRADA JESUS MANUEL	20	Ver horario
ICQ392	LABORATORIO DE INVESTIGACION	INGENIERÍA QUíMICA Y AMBIENTAL	1	BERGH OLIVARES LUIS GUILLERMO	40	Ver horario
ELO253	LABORATORIO DE LINEAS, GUIAS Y ANTENAS	ELECTRONICA	1	SOTO HERNANDEZ MARCELO ALFONSO	24	Ver horario
MET101	LABORATORIO DE MATERIALES Y PROCESOS	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	DE BARBIERI BOERO FLAVIO ANDRES	12	Ver horario
 	2	DE BARBIERI BOERO FLAVIO ANDRES	12	Ver horario
 	3	DE BARBIERI BOERO FLAVIO ANDRES	12	Ver horario
MET208	LABORATORIO DE MEDICIONES METALÚRGICAS	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	VALDERRAMA REYES WALDO	15	Ver horario
MET102	LABORATORIO DE METALURGIA EXTRACTIVA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	IBAÑEZ RIVERA JUAN PATRICIO	8	Ver horario
 	2	IBAÑEZ RIVERA JUAN PATRICIO	8	Ver horario
 	3	VALDERRAMA REYES WALDO	8	Ver horario
 	4	VALDERRAMA REYES WALDO	8	Ver horario
MAT283	LABORATORIO DE MODELACIÓN II	MATEMATICA	1	AGUIRRE OLEA PABLO	40	Ver horario
ELO314	LABORATORIO DE PROCESAMIENTO DIGITAL DE SEÑALES	ELECTRONICA	1	CARRASCO REYES GONZALO ARIEL	20	Ver horario
ICQ228	LABORATORIO DE PROCESOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	YIANATOS BERNARDINO JUAN	40	Ver horario
ILN255	LABORATORIO DE PROCESOS INDUSTRIALES	INDUSTRIAS	1	ORTUZAR MATURANA RODRIGO IVAN	40	Ver horario
 	2	ORTUZAR MATURANA RODRIGO IVAN	40	Ver horario
 	7	ORTUZAR MATURANA RODRIGO IVAN	40	Ver horario
TEL241	LABORATORIO DE REDES DE COMPUTADORES I	ELECTRONICA	1	SEPULVEDA RAMIREZ GERMAN GUSTAVO	40	Ver horario
ELO109	LABORATORIO ELECTRONICA B	ELECTRONICA	1	MARIN GONZALEZ GUSTAVO	24	Ver horario
 	2	RODRIGUEZ SCHULZ DANIEL	24	Ver horario
 	3	RODRIGUEZ SCHULZ DANIEL	24	Ver horario
 	4	JOFRE GONZALEZ MATIAS ANDRES	21	Ver horario
IMQ340	LEGISLACION AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	BONERT PUIG PAMELA ALEJANDRA	40	Ver horario
ICN324	LEGISLACION EMPRESARIAL	INDUSTRIAS	1	IRIARTE CORREA MACARENA FERNANDA	40	Ver horario
 	2	IRIARTE CORREA MACARENA FERNANDA	40	Ver horario
 	3	IRIARTE CORREA MACARENA FERNANDA	40	Ver horario
ICS008	LEGISLACION TRIBUTARIA	INGENIERÍA COMERCIAL	1	NN	40	Ver horario
 	2	MUÑOZ DIAZ PABLO ANDRES	40	Ver horario
ICS112	LEGISLACIÓN EMPRESARIAL	INGENIERÍA COMERCIAL	1	VALDIVIA GONZALEZ LORENA	40	Ver horario
HRW230	LENGUAJE MUSICAL DEL SIGLO XX	ESTUDIOS HUMANISTICOS	1	OLATE VALENZUELA SILVIO RENATO	40	Ver horario
INF253	LENGUAJES DE PROGRAMACIÓN	INFORMATICA	1	CASAS BARRIENTOS FRANCISCO JAVIER	60	Ver horario
ICS021	LIDERAZGO EMPRESARIAL	INGENIERÍA COMERCIAL	1	PACHECO GONZALEZ RUTH MIRIAM	40	Ver horario
ELO251	LINEAS DE TRANSMISION Y GUIAS DE ONDAS	ELECTRONICA	1	SOTO HERNANDEZ MARCELO ALFONSO	45	Ver horario
ICN370	LOGISTICA INDUSTRIAL	INDUSTRIAS	1	SANTIBAÑEZ JARA LEOPOLDO SAMUEL	40	Ver horario
ICS007	MACROECONOMIA	INGENIERÍA COMERCIAL	1	MALDONADO BUSTAMANTE PATRICIA	45	Ver horario
ILN211	MACROECONOMIA	INDUSTRIAS	1	SALAZAR ALBORNOZ RODOLFO IGNACIO	40	Ver horario
 	2	FUENTES ZEPEDA RAUL ANTONIO	40	Ver horario
ICN213	MACROECONOMIA II	INDUSTRIAS	1	FUENTES ZEPEDA RAUL ANTONIO	40	Ver horario
ICS012	MACROECONOMIA II	INGENIERÍA COMERCIAL	1	MALDONADO BUSTAMANTE PATRICIA	40	Ver horario
IMM260	MANDOS Y CONTROL	INGENIERÍA MECÁNICA	1	BREGANTE BACELLI ANDRES TOMAS	40	Ver horario
 	2	BREGANTE BACELLI ANDRES TOMAS	40	Ver horario
IMM240	MANTENCION INDUSTRIAL	INGENIERÍA MECÁNICA	2	VALDENEGRO OYANEDER RENE ANTONIO	40	Ver horario
MET224	MANUFACTURAS I	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	MANZO GARRIDO HERNAN JOAQUIN	40	Ver horario
MEC274	MANUFACTURAS III	INGENIERÍA MECÁNICA	1	MONSALVES CANUPI HUGO	40	Ver horario
IWQ207	MAQUINARIA INDUSTRIAL AUXILIAR	INGENIERÍA QUíMICA Y AMBIENTAL	1	JOFRE GONZALEZ MATIAS ANDRES	40	Ver horario
ELI222	MAQUINAS ELECTRICAS A	INGENIERÍA ELÉCTRICA	1	NORAMBUENA VALDIVIA MARGARITA ANDREA	40	Ver horario
ELI326	MAQUINAS ELECTRICAS I	INGENIERÍA ELÉCTRICA	1	JULIET AVILES JORGE ANDRES	40	Ver horario
ICN321	MARKETING	INDUSTRIAS	1	FERNANDEZ ROBIN ERNESTO CRISTOBAL	40	Ver horario
 	3	YAÑEZ MARTINEZ DIEGO IGNACIO	40	Ver horario
ICS017	MARKETING	INGENIERÍA COMERCIAL	1	PONTARELLI CONTRERAS FRANCESCO ANTONIO	40	Ver horario
ICS812	MARKETING DE NEGOCIOS Y SERVICIOS	INGENIERÍA COMERCIAL	1	PONTARELLI CONTRERAS FRANCESCO ANTONIO	40	Ver horario
ILN321	MARKETING E INVESTIGACIÓN DE MERCADOS	INDUSTRIAS	1	TRONCOSO SANGUESA RODRIGO ALEJANDRO	40	Ver horario
MAT215	MATEMATICA DISCRETA	MATEMATICA	1	TAN . JINGGANG	40	Ver horario
MAT011	MATEMATICA I	MATEMATICA	1	MORALES AYALA ANTONIO ANDRES	40	Ver horario
 	1	TORRES CABEZAS VICTOR GABRIEL	40	Ver horario
 	2	MADARIAGA ORELLANA PABLO EDUARDO	40	Ver horario
 	2	GONZALEZ YAÑEZ BETSABE DEL CARMEN	40	Ver horario
MAT021	MATEMATICA I	MATEMATICA	1	YANSEN NUNEZ SERGIO MANUEL	40	Ver horario
 	1	CABELLO GARMENDIA MARISOL	40	Ver horario
 	1	BARRIENTOS DIAZ SERGIO LUIS	40	Ver horario
 	2	YANSEN NUNEZ SERGIO MANUEL	40	Ver horario
 	2	ORTIZ COLLAO SEBASTIAN ELIAS	40	Ver horario
 	2	CABELLO GARMENDIA MARISOL	40	Ver horario
 	3	QUIJADA ZAMORA PABLO ANDRES	40	Ver horario
 	3	CABELLO GARMENDIA MARISOL	40	Ver horario
 	3	ASTUDILLO HIDALGO MARIA CECILIA	40	Ver horario
 	4	SOLIS MIQUIO MIGUEL ANGEL	40	Ver horario
 	4	AGUILERA MOYA ALEJANDRO MARCELO	40	Ver horario
 	4	ASTUDILLO HIDALGO MARIA CECILIA	40	Ver horario
 	5	YANSEN NUNEZ SERGIO MANUEL	40	Ver horario
 	5	AVILES RIELOFF ELIZABETH MARGARITA	40	Ver horario
 	5	VÁSQUEZ SALDÍAS PATRICIA	40	Ver horario
 	6	VELIZ RETAMALES SERGIO ANDRES	40	Ver horario
 	6	NN	40	Ver horario
 	6	GUAJARDO ALIAGA NANCY MARISOL	40	Ver horario
 	7	SOLIS MIQUIO MIGUEL ANGEL	40	Ver horario
 	7	ASTUDILLO HIDALGO MARIA CECILIA	40	Ver horario
 	7	VILCHES CONTRERAS VICTOR WENCESLAO	40	Ver horario
 	8	SCHWARZENBERG MILLAR CARLOS ALEJANDRO	40	Ver horario
 	8	TAN . JINGGANG	40	Ver horario
 	8	LOPEZ CEPEDA PATRICIA	40	Ver horario
 	9	AGUILERA MOYA ALEJANDRO MARCELO	40	Ver horario
 	9	TOLEDO TORRES PATRICIO ALEJANDRO	40	Ver horario
 	9	VILCHES CONTRERAS VICTOR WENCESLAO	40	Ver horario
 	10	VIDELA MUÑOZ LEONARDO ANDRES	40	Ver horario
 	10	GALVEZ DIAZ SEBASTIAN ANDRES	40	Ver horario
 	10	SILVA GONZALEZ MAGDA C	40	Ver horario
 	11	CONTRERAS BARRAZA FABIAN	40	Ver horario
 	11	TUMA ABUFOM ELIAS	40	Ver horario
 	11	NN	40	Ver horario
 	12	NN	40	Ver horario
 	12	ASTUDILLO HIDALGO MARIA CECILIA	40	Ver horario
 	12	MATURANA PEÑA ISABEL	40	Ver horario
 	13	SOLIS MIQUIO MIGUEL ANGEL	40	Ver horario
 	13	LABBE ZEPEDA ARTURO	40	Ver horario
 	13	VILCHES CONTRERAS VICTOR WENCESLAO	40	Ver horario
 	14	MADARIAGA ORELLANA PABLO EDUARDO	40	Ver horario
 	14	YEMINI CABALEIRO BRUNO JAVIER	40	Ver horario
 	14	NN	40	Ver horario
 	15	NN	40	Ver horario
 	15	ASTUDILLO HIDALGO MARIA CECILIA	40	Ver horario
 	15	MATURANA PEÑA ISABEL	40	Ver horario
 	16	AGUILERA MOYA ALEJANDRO MARCELO	40	Ver horario
 	16	MATURANA PEÑA ISABEL	40	Ver horario
 	16	GUAJARDO ALIAGA NANCY MARISOL	40	Ver horario
 	17	VIDAL OLIVERO ALEJANDRO ANDRES	40	Ver horario
 	17	BRICEÑO VALENCIA VERONICA ESTHER	40	Ver horario
 	18	AVILES RIELOFF ELIZABETH MARGARITA	40	Ver horario
 	18	RIQUELME JERIA GONZALO	40	Ver horario
 	18	NN	40	Ver horario
 	19	VELIZ RETAMALES SERGIO ANDRES	40	Ver horario
 	19	RIQUELME JERIA GONZALO	40	Ver horario
 	19	NN	40	Ver horario
 	20	JIMENEZ HUGHES JUAN ENRIQUE	40	Ver horario
 	20	NN	40	Ver horario
 	20	VILCHES CONTRERAS VICTOR WENCESLAO	40	Ver horario
 	21	YAÑEZ CORNEJO CAMILA FRANCISCA	40	Ver horario
 	21	ERRAZ LEVAGGI DANIEL ANDRES	40	Ver horario
 	50	SZANTO NAREA IVAN	32	Ver horario
MAT012	MATEMATICA II	MATEMATICA	2	BRICEÑO VALENCIA VERONICA ESTHER	40	Ver horario
MAT022	MATEMATICA II	MATEMATICA	1	PEREZ OJEDA JAVIER IGNACIO	40	Ver horario
 	1	NN	40	Ver horario
 	2	VELIZ RETAMALES SERGIO ANDRES	40	Ver horario
 	2	YAÑEZ CORNEJO CAMILA FRANCISCA	40	Ver horario
 	3	MAULEN YANEZ MARIA ANGELICA	40	Ver horario
 	3	VILCHES CONTRERAS VICTOR WENCESLAO	40	Ver horario
 	4	HENRIQUEZ CASTRO ESTEBAN	40	Ver horario
 	4	MATURANA PEÑA ISABEL	40	Ver horario
 	5	MORALES AYALA ANTONIO ANDRES	40	Ver horario
 	5	TORRES CABEZAS VICTOR GABRIEL	40	Ver horario
 	6	PEREZ OJEDA JAVIER IGNACIO	40	Ver horario
 	6	NN	40	Ver horario
 	7	TUMA ABUFOM ELIAS	40	Ver horario
 	7	LOPEZ CEPEDA PATRICIA	40	Ver horario
 	9	NN	40	Ver horario
 	9	FIGUEROA REBOLLEDO GLADYS	40	Ver horario
 	10	HENRIQUEZ CASTRO ESTEBAN	40	Ver horario
 	10	BAZAN DIAZ WILMER ORLANDO	40	Ver horario
 	11	HENRIQUEZ CASTRO ESTEBAN	40	Ver horario
 	11	BAZAN DIAZ WILMER ORLANDO	40	Ver horario
 	12	YAÑEZ CORNEJO CAMILA FRANCISCA	40	Ver horario
 	12	JARA CIFUENTES SEBASTIAN NICOLAS	40	Ver horario
MAT013	MATEMATICA III	MATEMATICA	1	GUAJARDO ALIAGA NANCY MARISOL	50	Ver horario
 	2	MORALES AYALA ANTONIO ANDRES	50	Ver horario
MAT014	MATEMATICA IV	MATEMATICA	1	TRONCOSO URIBE CLAUDIO	60	Ver horario
 	2	TRONCOSO URIBE CLAUDIO	60	Ver horario
MAT023	MATEMATICAS III	MATEMATICA	1	CABRERA BIANCHETTI ALDO ANTONIO	45	Ver horario
 	2	AGUILERA MOYA ALEJANDRO MARCELO	45	Ver horario
 	3	ORELLANA ESTAY OSCAR FERNANDO	45	Ver horario
 	4	TAPIA CARO JOSE ANDRES	45	Ver horario
 	5	CONTRERAS BARRAZA FABIAN	45	Ver horario
 	6	RIQUELME FLORES VICTOR HUGO	45	Ver horario
 	7	VELIZ RETAMALES SERGIO ANDRES	45	Ver horario
 	9	VILCHES CONTRERAS VICTOR WENCESLAO	45	Ver horario
 	10	VELIZ RETAMALES SERGIO ANDRES	45	Ver horario
 	11	VILLAR SEPULVEDA EDGARDO ENRIQUE	45	Ver horario
 	12	GUAJARDO ALIAGA NANCY MARISOL	45	Ver horario
 	13	JIMENEZ HUGHES JUAN ENRIQUE	45	Ver horario
MAT024	MATEMATICAS IV	MATEMATICA	1	OLIVARES BARRIENTOS MIGUEL ANGEL	40	Ver horario
 	2	BAZAN DIAZ WILMER ORLANDO	40	Ver horario
 	3	HENRIQUEZ CASTRO ESTEBAN	40	Ver horario
 	4	BAZAN DIAZ WILMER ORLANDO	40	Ver horario
 	5	OLIVARES BARRIENTOS MIGUEL ANGEL	40	Ver horario
 	6	CABRERA BIANCHETTI ALDO ANTONIO	40	Ver horario
 	7	TUMA ABUFOM ELIAS	40	Ver horario
 	8	ORELLANA ESTAY OSCAR FERNANDO	40	Ver horario
 	9	TUMA ABUFOM ELIAS	40	Ver horario
MAT015	MATEMATICAS V	MATEMATICA	1	GALVEZ DIAZ SEBASTIAN ANDRES	40	Ver horario
MAT050	MATEMÁTICA I PARA ARQUITECTURA	MATEMATICA	1	VIDAL OLIVERO ALEJANDRO ANDRES	45	Ver horario
 	2	TORRES CABEZAS VICTOR GABRIEL	45	Ver horario
MAT051	MATEMÁTICA II PARA ARQUITECTURA	MATEMATICA	1	MORALES AYALA ANTONIO ANDRES	45	Ver horario
MAT052	MATEMÁTICA III PARA ARQUITECTURA	MATEMATICA	1	TORRES CABEZAS VICTOR GABRIEL	50	Ver horario
IWC203	MATERIALES PARA INGENIERIA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	ESTAY VILLALON SERGIO	60	Ver horario
MET203	MATERIALES PARA INGENIERÍA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	MANZO GARRIDO ITALO IGNACIO	60	Ver horario
MET324	MATERIALES, FUNCION Y PROCESOS	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	MANZO GARRIDO HERNAN JOAQUIN	40	Ver horario
FIS310	MECANICA CLASICA	FISICA	1	SIDDIKOV . MARAT	20	Ver horario
FIS340	MECANICA CUANTICA I	FISICA	1	ORELLANA DINAMARCA PEDRO	40	Ver horario
 	2	NN	40	Ver horario
 	3		20	Ver horario
IWM220	MECANICA DE FLUIDOS GENERAL	INGENIERÍA MECÁNICA	2	FLORES MARADIAGA ALEX GEOVANNY	40	Ver horario
ILM222	MECANICA DE FLUIDOS II	INGENIERÍA MECÁNICA	1	COOPER VILLAGRAN CHRISTOPHER	50	Ver horario
CON260	MECANICA DE SUELOS I Y LABORATORIO	OBRAS CIVILES	1	PETERSEN ACEVEDO MIGUEL	50	Ver horario
CIV366	MECANICA DE SUELOS II	OBRAS CIVILES	1	SILVA ILLANES MATIAS FELIPE	60	Ver horario
FIS330	MECANICA ESTADISTICA	FISICA	1	CORRALES ITURRIAGA TOMAS PATRICIO	40	Ver horario
 	2	CORRALES ITURRIAGA TOMAS PATRICIO	20	Ver horario
IWM151	MECANICA GENERAL	INGENIERÍA MECÁNICA	2	GONZALEZ BAQUEDANO GUILLERMO	50	Ver horario
FIS210	MECANICA INTERMEDIA I	FISICA	1	GONZALEZ PINOCHET MARCELA PAZ	40	Ver horario
FIS211	MECANICA INTERMEDIA II	FISICA	1	SIDDIKOV . MARAT	40	Ver horario
CIV202	MECANICA RACIONAL	OBRAS CIVILES	1	ARAYA NIETO VICTOR ALEJANDRO	80	Ver horario
MEC120	MECÁNICA DE FLUIDOS	INGENIERÍA MECÁNICA	1	ZAMBRANO RODRIGUEZ HARVEY ALEXANDER	40	Ver horario
IPO416	MECÁNICA DE FLUIDOS AVANZADA	OBRAS CIVILES	1	WILLIAMS . MEGAN ELIZABETH	30	Ver horario
MEC220	MECÁNICA DE FLUIDOS AVANZADA	INGENIERÍA MECÁNICA	1	COOPER VILLAGRAN CHRISTOPHER	40	Ver horario
CIV133	MECÁNICA DE MATERIALES	OBRAS CIVILES	1	TOBAR RAMOS RENE ENRIQUE	70	Ver horario
MEC255	MECÁNICA DE MATERIALES	INGENIERÍA MECÁNICA	1	PACHECO SANJUAN ALEJANDRO ANDRES	50	Ver horario
MEC353	MECÁNICA DE MÁQUINAS	INGENIERÍA MECÁNICA	1	ROJAS GONZALEZ FERNANDO	40	Ver horario
IPO903	MECÁNICA DE ROCAS	OBRAS CIVILES	1	RODRIGUEZ SAAVEDRA PATRICIA	20	Ver horario
IQA221	MECÁNICA DE SISTEMAS FLUIDOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	LAZO ACUÑA ANDREA PAOLA	40	Ver horario
IWM160	MEDICIONES MECANICAS GENERALES	INGENIERÍA MECÁNICA	1	ALVAREZ SAAVEDRA SERGIO	40	Ver horario
MEC260	MEDICIONES MECÁNICAS	INGENIERÍA MECÁNICA	1	ALVAREZ SAAVEDRA SERGIO	40	Ver horario
TEL308	MEMORIA DE TIT.PARA ING.CIVIL TELEMATICO	ELECTRONICA	1	NN	2	Ver horario
ELI380	MEMORIA DE TITULACION	INGENIERÍA ELÉCTRICA	1	PULIDO VENEGAS ESTEBAN SAMUEL	6	Ver horario
 	2	ANGULO CARDENAS ALEJANDRO ALBER	1	Ver horario
 	2	NORAMBUENA VALDIVIA MARGARITA ANDREA	1	Ver horario
 	3	HINOJOSA MATEUS VICTOR HUGO	5	Ver horario
 	3	PORZIO LOPEZ ALEJANDRO	5	Ver horario
 	4	LEZANA ILLESCA PABLO ANDRES	1	Ver horario
 	5	LEZANA ILLESCA PABLO ANDRES	1	Ver horario
 	5	JULIET AVILES JORGE ANDRES	1	Ver horario
 	6	RIOS VIELMA JAVIER IGNACIO	1	Ver horario
 	6	RENDIC DAVIS RAUL	1	Ver horario
 	7	GIL SAGAS ESTEBAN MANUEL	1	Ver horario
 	7	SOTO SEPULVEDA EDUARDO ANDRES	1	Ver horario
 	8	ANGULO CARDENAS ALEJANDRO ALBER	2	Ver horario
ELO308	MEMORIA DE TITULACION PARA ING. CIVIL ELO.	ELECTRONICA	1	EQUIPO	50	Ver horario
ELI390	MEMORIA DE TITULACIÓN	INGENIERÍA ELÉCTRICA	1	ANGULO CARDENAS ALEJANDRO ALBER	1	Ver horario
 	2	GIL SAGAS ESTEBAN MANUEL	1	Ver horario
 	3	RIOS VIELMA JAVIER IGNACIO	1	Ver horario
 	3	HINOJOSA MATEUS VICTOR HUGO	1	Ver horario
 	4	RIOS VIELMA JAVIER IGNACIO	1	Ver horario
 	4	MONTAÑA CHAPARRO JOHNY HERNÁN	1	Ver horario
 	8	ANGULO CARDENAS ALEJANDRO ALBER	2	Ver horario
MET392	MEMORIA DE TITULACIÓN	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	TELLO ARAYA KAREM EVA	40	Ver horario
MAT308	MEMORIA DE TÍTULO	MATEMATICA	2	ALARCON ARANEDA SALOMON DIOGENES	1	Ver horario
 	3	VALLE VIDAL CARLOS ANTONIO	3	Ver horario
 	4	VALLEJOS ARRIAGADA RONNY OBED	1	Ver horario
IWG399	MEMORIAS MULTIDISCIPLINARIAS: EMPRENDIMIENTO	DIRECCION GRAL. DOCENCIA	1	EQUIPO	40	Ver horario
IWG397	MEMORIAS MULTIDISCIPLINARIAS: INNOVACIÓN	DIRECCION GRAL. DOCENCIA	1	EQUIPO	40	Ver horario
IWG396	MEMORIAS MULTIDISCIPLINARIAS: TRANSVERSAL 1	DIRECCION GRAL. DOCENCIA	1	EQUIPO	40	Ver horario
IWG398	MEMORIAS MULTIDISCIPLINARIAS: TRANSVERSAL 2	DIRECCION GRAL. DOCENCIA	1	EQUIPO	40	Ver horario
ICS814	MERCADO DE CAPITALES	INGENIERÍA COMERCIAL	1	NN	40	Ver horario
MET227	METALURGIA FÍSICA II	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	ESTAY VILLALON SERGIO	40	Ver horario
ILC204	METALURGIA Y MATERIALES	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	ZUMAETA BUSTAMANTE JULIO OMAR	40	Ver horario
MRA401	METODOLOGÍAS DE LA INVESTIGACIÓN	ARQUITECTURA	1	HORMAZABAL POBLETE NINA AMOR	20	Ver horario
FIS380	METODOS MATEMATICOS DE LA FISICA	FISICA	1	CASTILLO FELISOLA OSCAR	20	Ver horario
IPD410	METODOS MATEMATICOS EN CONTROL AUTOMATIC	ELECTRONICA	1	YUZ EISSMANN JUAN IGNACIO	20	Ver horario
ELI214	METROLOGIA ELECTRICA	INGENIERÍA ELÉCTRICA	1	RIOS VIELMA JAVIER IGNACIO	40	Ver horario
IQA102	MICROBIOLOGÍA AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	MERY ARAYA CAMILA DEL PILAR	40	Ver horario
ICS005	MICROECONOMIA	INGENIERÍA COMERCIAL	1	TAPIA GERTOSIO JUAN FRANCISCO	40	Ver horario
 	2	DIAZ ACOSTA ORIELLE VIVIANA	40	Ver horario
ILN210	MICROECONOMIA	INDUSTRIAS	1	SALAZAR ALBORNOZ RODOLFO IGNACIO	40	Ver horario
 	2	SALAZAR ALBORNOZ RODOLFO IGNACIO	40	Ver horario
ICS006	MICROECONOMIA II	INGENIERÍA COMERCIAL	1	GATICA SILVA MACARENA	45	Ver horario
ICS162	MICROECONOMÍA I	INGENIERÍA COMERCIAL	1	TAPIA GERTOSIO JUAN FRANCISCO	40	Ver horario
TEL354	MINERÍA DE DATOS	ELECTRONICA	1	ARAYA LOPEZ MAURICIO ALEJANDRO	40	Ver horario
HFW136	MISTERIOS Y TRADICIONES DE LA CULTURA RAPA NUI	ESTUDIOS HUMANISTICOS	1	RAMIREZ ALIAGA JOSE MIGUEL	20	Ver horario
IMQ300	MODELACION AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	GARCIA GEN SANTIAGO	40	Ver horario
IDP205	MODELACION DE PRODUCTOS	Ingeniería en Diseño	1	ROZAS UBILLA CRISTOPHER ALEXANDER	40	Ver horario
INF393	MÁQUINAS DE APRENDIZAJE	INFORMATICA	1	VALLE VIDAL CARLOS ANTONIO	40	Ver horario
ELI322	MÁQUINAS ELÉCTRICAS C	INGENIERÍA ELÉCTRICA	1	FUENTES FUENTEALBA RICARDO	40	Ver horario
INF377	MÉTODOS DE DISEÑO CENTRADO EN USUARIOS	INFORMATICA	1	LOPEZ MONCADA CLAUDIA	40	Ver horario
FIS245	MÉTODOS DE LA FÍSICA MATEMÁTICA	FISICA	1	CASTILLO FELISOLA OSCAR	40	Ver horario
MEC270	MÉTODOS NUMÉRICOS EN INGENIERÍA MECÁNICA	INGENIERÍA MECÁNICA	1	GERS . ROMAIN JEAN-MICHEL	40	Ver horario
EFI111	NATACIÓN	DEFIDER	1	ROMPELTIEN MENDEZ MARCELA ALEJANDRA	30	Ver horario
 	2	ROMPELTIEN MENDEZ MARCELA ALEJANDRA	30	Ver horario
IWQ294	OPERACION DE PLANTAS	INGENIERÍA QUíMICA Y AMBIENTAL	1	NN	54	Ver horario
ELI349	OPERACION DE SIST.ELECTRICOS DE POTENCIA	INGENIERÍA ELÉCTRICA	1	ANGULO CARDENAS ALEJANDRO ALBER	40	Ver horario
FIS222	OPTICA	FISICA	1	LANDEROS SILVA PEDRO MIGUEL	40	Ver horario
INF292	OPTIMIZACIÓN	INFORMATICA	1	FERNANDEZ GIL ALEJANDRO	40	Ver horario
MAT379	OPTIMIZACIÓN Y CONTROL	MATEMATICA	1	GUZMAN MELENDEZ PATRICIO RICARDO	40	Ver horario
ICN212	ORGANIZACION INDUSTRIAL	INDUSTRIAS	1	SALAZAR ALBORNOZ RODOLFO IGNACIO	40	Ver horario
ICS011	ORGANIZACION INDUSTRIAL	INGENIERÍA COMERCIAL	1	GATICA SILVA MACARENA	40	Ver horario
INF270	ORGANIZACIONES Y SISTEMAS DE INFORMACIÓN	INFORMATICA	1	LOPEZ MONCADA CLAUDIA	60	Ver horario
HFW130	PANORAMA DE LAS CIVILIZACIONES ACTUALES	ESTUDIOS HUMANISTICOS	1	MUÑOZ BUSTAMANTE EDUARDO	40	Ver horario
TEL360	PENSAMIENTO DE DISEÑO EN INGENIERÍA	ELECTRONICA	1	SCHELE EGAÑA PABLO ANDRES	40	Ver horario
MET236	PIROMETALURGIA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	HENAO ZAPATA HECTOR MARIO	40	Ver horario
ICS857	PLANIFICACION DE EMPRESAS	INGENIERÍA COMERCIAL	1	CHAVEZ VELASQUEZ HARDY OMAR	40	Ver horario
ELI350	PLANIFICACION ELECTRICA	INGENIERÍA ELÉCTRICA	1	BENARIO TRONCOSO PABLO	40	Ver horario
ELI344	PLANIFICACIÓN DE SISTEMAS ELÉCTRICOS	INGENIERÍA ELÉCTRICA	1	BENARIO TRONCOSO PABLO	40	Ver horario
ICS870	PLANIFICACIÓN ECONÓMICA	INGENIERÍA COMERCIAL	1	RUBIO ROMERO PATRICIO	40	Ver horario
HRW153	PRACTICA EN ACCION COMUNITARIA	ESTUDIOS HUMANISTICOS	1	MERCADAL GONZALEZ PAULINA TERESA	40	Ver horario
 	2	DIAZ DE LA FUENTE TATIANA MAGALY	40	Ver horario
 	3	MERCADAL GONZALEZ PAULINA TERESA	40	Ver horario
 	4	MERCADAL GONZALEZ PAULINA TERESA	40	Ver horario
 	5	JERIA MADARIAGA LUZ MARIA	40	Ver horario
MATE11	PRE-CÁLCULO	MATEMATICA	1	GODOY MUTUS DE LA PARRA PAMELA CONSTANZA	40	Ver horario
 	2	MADARIAGA ORELLANA PABLO EDUARDO	40	Ver horario
 	3	YAÑEZ CORNEJO CAMILA FRANCISCA	40	Ver horario
PRE001	PRE-UNIVERSITARIO	DIRECCION DE ESTUDIO	1	NN	0	Ver horario
 	2		0	Ver horario
 	3		0	Ver horario
 	4		0	Ver horario
 	5		0	Ver horario
 	6		0	Ver horario
 	7		0	Ver horario
 	8		0	Ver horario
 	9		0	Ver horario
 	10		0	Ver horario
 	11		0	Ver horario
 	12		0	Ver horario
 	13		0	Ver horario
 	14		0	Ver horario
MAT041	PROBABILIDAD Y ESTADISTICA	MATEMATICA	2	NN	40	Ver horario
MAT032	PROBABILIDAD Y ESTADISTICA COMERCIAL	MATEMATICA	1	VILLALOBOS TORRES HUMBERTO MARCELO	40	Ver horario
 	2	VILLALOBOS TORRES HUMBERTO MARCELO	40	Ver horario
MAT042	PROBABILIDAD Y ESTADISTICA INDUSTRIAL	MATEMATICA	4	VILLALOBOS TORRES HUMBERTO MARCELO	50	Ver horario
 	6	VIDELA JIMENEZ PATRICIO JAVIER	50	Ver horario
MAT044	PROBABILIDAD Y ESTADÍSTICA PARA INGENIERÍA CIVIL	MATEMATICA	1	VALLEJOS ARRIAGADA RONNY OBED	40	Ver horario
IPD431	PROBABILIDAD Y PROCESOS ALEATORIOS	ELECTRONICA	1	VARGAS PARRA FRANCISCO JAVIER	20	Ver horario
ELO313	PROCESAMIENTO DIGITAL DE SEÑALES CON APLICACIONES	ELECTRONICA	1	ZAÑARTU SALAS MATIAS	40	Ver horario
INF333	PROCESO DE CREACIÓN DE VIDEOJUEGOS	INFORMATICA	1	VON BRAND LAREDO SVEN	40	Ver horario
IWQ227	PROCESOS DE ALIMENTOS II	INGENIERÍA QUíMICA Y AMBIENTAL	1	NN	40	Ver horario
MEC161	PROCESOS DE MANUFACTURA	INGENIERÍA MECÁNICA	1	MENA YANSSEN RAFAEL	40	Ver horario
IWM276	PROCESOS DE MANUFACTURA II	INGENIERÍA MECÁNICA	1	MENA YANSSEN RAFAEL	40	Ver horario
IPD436	PROCESOS ESTOCASTICOS Y TEORIA DE FILAS	ELECTRONICA	1	VALLEJOS CAMPOS REINALDO ANTONIO	20	Ver horario
MEC372	PRODUCCION	INGENIERÍA MECÁNICA	1	BREGANTE BACELLI ANDRES TOMAS	40	Ver horario
LASPAU	PROGRAMA ACADÉMICO Y PROFESIONAL PARA LAS AMÉRICAS	DIRECCION GRAL. DOCENCIA	1		0	Ver horario
 	2		0	Ver horario
IWI131	PROGRAMACION	INFORMATICA	1	VASQUEZ GUERRA ANDREA FERNANDA	40	Ver horario
 	2	FUENTES ZENTENO ROBERTO FELIPE	40	Ver horario
 	3	SAN MARTIN REYES DANIEL EDUARDO	40	Ver horario
 	4	ORMEÑO ARRIAGADA PABLO IVAN	30	Ver horario
 	5	LEON VASQUEZ ROBERTO JESUS	40	Ver horario
 	6	ALLENDE CID HECTOR GABRIEL	40	Ver horario
 	7	MALDONADO CARMONA JAVIER ALEXIS	40	Ver horario
 	8	GUEVARA ALBORNOZ MIGUEL ROBERTO	40	Ver horario
 	9	BIELENBERG GUZMAN MABEL A.	40	Ver horario
 	10	ULLOA POBLETE GUSTAVO JORGE	40	Ver horario
 	11	CAMPOS CHARTIER SERGIO MANUEL	28	Ver horario
 	12	VARAS ASTUDILLO MIGUEL ANGEL	28	Ver horario
 	13	SALINAS EVANGELISTA ALVARO SIMON	28	Ver horario
 	14	VELOZ BAEZA ALEJANDRO ANDRES	40	Ver horario
 	15	PEZOA RIVERA RAQUEL ANDREA	28	Ver horario
 	16	FIGUEROA RETAMAL ANDREA BELEN	40	Ver horario
 	17	IBARRA SEPULVEDA PABLO NICOLAS	28	Ver horario
 	18	CAMPOS CHARTIER SERGIO MANUEL	40	Ver horario
 	19	FERNANDEZ GIL ALEJANDRO	40	Ver horario
 	20	GOMEZ SANCHEZ MARIAM	40	Ver horario
 	21	GUEVARA ALBORNOZ MIGUEL ROBERTO	40	Ver horario
 	22	FERNANDEZ GIL ALEJANDRO	40	Ver horario
INF349	PROGRAMACIÓN COMPETITIVA 1	INFORMATICA	1	BUIL ARANDA CARLOS	40	Ver horario
ILI257	PROGRAMACIÓN PARALELA APLICADA	INFORMATICA	1	BONNAIRE . XAVIER EMMANUEL	40	Ver horario
INF130	PROGRAMACIÓN Y TRATAMIENTO DE DATOS PARA LA GESTIÓN	INFORMATICA	1	GUEVARA ALBORNOZ MIGUEL ROBERTO	40	Ver horario
 	2	ORMEÑO ARRIAGADA PABLO IVAN	40	Ver horario
 	3	SALINAS EVANGELISTA ALVARO SIMON	40	Ver horario
 	4	VASQUEZ GUERRA ANDREA FERNANDA	40	Ver horario
 	5	LAZO ROBAINA YOSLANDY	40	Ver horario
 	6	MONTENEGRO TAPIA GABRIELA PATRICIA	40	Ver horario
 	7	BIELENBERG GUZMAN MABEL A.	40	Ver horario
 	8	MONTENEGRO TAPIA GABRIELA PATRICIA	40	Ver horario
CON320	PROPUESTAS Y LICITACIONES	OBRAS CIVILES	1	NN	60	Ver horario
PII438	PROSPECTIVA Y PLANIFICACIÓN ESTRATÉGICA	INDUSTRIAS	1	SAAVEDRA RODRIGUEZ OSCAR JULIO	20	Ver horario
ELI342	PROTECCIONES ELECTRICAS	INGENIERÍA ELÉCTRICA	1	PULIDO VENEGAS ESTEBAN SAMUEL	40	Ver horario
MAT301	PROYECTO DE MEMORIA DE TITULACIÓN	MATEMATICA	2	KARKULIK . MICHAEL	5	Ver horario
 	3	VALLE VIDAL CARLOS ANTONIO	5	Ver horario
TEL307	PROYECTO DE TIT. PARA ING.C. TELEMATICO	ELECTRONICA	1	EQUIPO	40	Ver horario
ELO307	PROYECTO DE TITULACION PARA ING. CIVIL ELO.	ELECTRONICA	1	EQUIPO	50	Ver horario
ARQ650	PROYECTO DE TITULACIÓN	ARQUITECTURA	1	SERRANO RODRIGUEZ PEDRO ROLANDO	5	Ver horario
 	2	HORMAZABAL POBLETE NINA AMOR	5	Ver horario
 	3	HURTADO SALDIAS MARCELA	5	Ver horario
 	4	SOTO CARO MARCELA ANDREA	5	Ver horario
 	5	GONZALEZ BOHME LUIS FELIPE	5	Ver horario
 	6	BARROS LAFUENTE LUIS PABLO	5	Ver horario
 	7	GALVEZ HUERTA MIGUEL ANGEL	5	Ver horario
 	8	SOLIS FIGUEROA RAUL ALEJANDRO	5	Ver horario
 	9	LEON CANALES JORGE ENRIQUE	5	Ver horario
 	10	MAINO ANSALDO SANDRO	5	Ver horario
 	11	VALDES CASTILLO FRANCISCO JAVIER	5	Ver horario
 	12	CARRASCO WALBURG CAROLINA ANDREA	5	Ver horario
 	13	SARABIA FUENTES GUSTAVO	5	Ver horario
 	14	IBARRA SOTO FRANCISCO JAVIE	5	Ver horario
 	15	BASTIAS GOMEZ FREDDY ANTONIO	5	Ver horario
 	16	SILVA GOPFERT PABLO ANDRES	5	Ver horario
 	17	CASTRO GONZALEZ CARLOS JULIO	5	Ver horario
 	18	QUITRAL ZAPATA FRANCISCO JAVIER	5	Ver horario
 	19	GLARIA KAHNI AMAYA	5	Ver horario
 	20	SILLS GARRIDO PABLO	5	Ver horario
 	21	CACERES CORVALAN KATHERINE JACQUELINE	5	Ver horario
 	22	CALVO CASTILLO FRANCISCO JAVIER	5	Ver horario
IMQ381	PROYECTO EN INGENIERIA AMBIENTAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	ZAVALA OLAVE ROSA MARIA	40	Ver horario
MET370	PROYECTO METALÚRGICO I	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	VIDAL QUEVEDO GUILLERMO RICARDO	40	Ver horario
MET380	PROYECTO METALÚRGICO II	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	ZUMAETA BUSTAMANTE JULIO OMAR	40	Ver horario
CIV391	PROYECTO VIAL	OBRAS CIVILES	1	WAHR DANIEL CARLOS	40	Ver horario
ICQ381	PROYECTOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	NN	40	Ver horario
ICS025	PROYECTOS	INGENIERÍA COMERCIAL	1	SOTO YAÑEZ CARLOS HUMBERTO	40	Ver horario
 	2	OSORIO ZELADA HUGO ANTONIO	40	Ver horario
ELI377	PROYECTOS ELECTRICOS A	INGENIERÍA ELÉCTRICA	1	RENDIC DAVIS RAUL	40	Ver horario
ELI378	PROYECTOS ELECTRICOS I	INGENIERÍA ELÉCTRICA	1	GIL SAGAS ESTEBAN MANUEL	40	Ver horario
ELO302	PROYECTOS ELECTRONICOS	ELECTRONICA	1	LIBERONA DE LA FUENTE JOSE DARIO	50	Ver horario
ICQ382	PROYECTOS ESPECIFICOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	RAMIREZ LIVINGSTON DANIEL ALBERTO	40	Ver horario
IMQ391	PROYECTOS ESPECÍFICOS AMBIENTALES	INGENIERÍA QUíMICA Y AMBIENTAL	1	HOMSI AUCHEN JACOBO	40	Ver horario
CIV349	PROYECTOS HIDRAULICOS	OBRAS CIVILES	1	ARAYA MENA JORGE JOSE	70	Ver horario
HRW111	PSICOLOGIA INDUSTRIAL	ESTUDIOS HUMANISTICOS	1	VERGARA SAAVEDRA MARIO	40	Ver horario
QUI224	QUIMICA ANALITICA CUANTITATIVA I	QUIMICA	1	VALENZUELA SOBARZO FERMIN ANIBAL	40	Ver horario
QUI021	QUIMICA BASICA	QUIMICA	1	ARRIAGADA ROMERO ANDRES IGNACIO	70	Ver horario
QUI022	QUIMICA DE MATERIALES	QUIMICA	1	THOMET ISLA FRANZ ANDRES	80	Ver horario
QUI216	QUIMICA INORGANICA II	QUIMICA	1	THOMET ISLA FRANZ ANDRES	40	Ver horario
QUI238	QUIMICA ORGANICA II	QUIMICA	1	TABORGA MORALES LAUTARO LIBER	40	Ver horario
QUI010	QUIMICA Y SOCIEDAD	QUIMICA	1	MORGADO ESPINOZA CLAUDIO ANDRES	40	Ver horario
 	2	SANCHEZ GONZALEZ RODRIGO ANDRES	40	Ver horario
 	3	DOMINGUEZ BARCELO ANA MARIA	40	Ver horario
 	4	DOMINGUEZ BARCELO ANA MARIA	40	Ver horario
 	5	GALLARDO ARAYA CLAUDIO MANUEL	40	Ver horario
 	6	CERECEDA BALIC FRANCISCO	40	Ver horario
 	7	CAUTIVO SERRANO TERESA	40	Ver horario
 	8	CAUTIVO SERRANO TERESA	40	Ver horario
 	9	SANCHEZ GONZALEZ RODRIGO ANDRES	40	Ver horario
 	10	CAMPOS DERAMOND ANA MARIA	40	Ver horario
 	11	CAMPOS DERAMOND ANA MARIA	40	Ver horario
 	12	CHAVEZ CORTES MARIA ISABEL	40	Ver horario
 	13	PINTER . BALAZS	40	Ver horario
 	14	IMBARACK CANDIA ELIZABETH JAZMIN	40	Ver horario
 	15	TABORGA MORALES LAUTARO LIBER	40	Ver horario
 	16	BAEZA MATURANA EVELYN DEL CARMEN	40	Ver horario
 	17	RESTREPO VALLADARES SUSANA	40	Ver horario
 	18	BAEZA MATURANA EVELYN DEL CARMEN	40	Ver horario
 	19	CHAVEZ CORTES MARIA ISABEL	40	Ver horario
 	20	ARRIECHE POLANCO DIONI ANTONIO	40	Ver horario
 	21	GALLARDO ARAYA CLAUDIO MANUEL	40	Ver horario
QUI026	QUÍMICA BÁSICA	QUIMICA	1	REVECO OLIVARES PATRICIO	90	Ver horario
QUI025	QUÍMICA DE PROCESOS	QUIMICA	1	FAUNDEZ LEIVA MARTIN GABRIEL	90	Ver horario
 	2	FAUNDEZ LEIVA MARTIN GABRIEL	90	Ver horario
QUI028	QUÍMICA ORGÁNICA	QUIMICA	1	ESPINOZA CATALAN LUIS JAVIER	40	Ver horario
AYQ011	QYUD. QCA. BASICA-EJEC.	QUIMICA	1	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
 	2	OLLINO ORDENES MARIO ALBERTO	30	Ver horario
INF391	RECONOCIMIENTO DE PATRONES EN MINERÍA DE DATOS	INFORMATICA	1	SALAS FUENTES RODRIGO JOSE	40	Ver horario
ICN323	RECURSOS HUMANOS	INDUSTRIAS	1	DE LA FUENTE MUÑOZ FRANCISCO JAVIER	40	Ver horario
 	2	DE LA FUENTE MUÑOZ FRANCISCO JAVIER	40	Ver horario
 	3	BOSCO LOSADA ALESSANDRA FRANCESCA	40	Ver horario
ICS015	RECURSOS HUMANOS	INGENIERÍA COMERCIAL	1	PACHECO GONZALEZ RUTH MIRIAM	40	Ver horario
INF256	REDES DE COMPUTADORES	INFORMATICA	1	CAÑAS ROBLES JAVIER	40	Ver horario
ELO322	REDES DE COMPUTADORES I	ELECTRONICA	1	GONZALEZ VALENZUELA AGUSTIN JOSE	60	Ver horario
TEL329	REDES DE SENSORES	ELECTRONICA	1	AHMED ABDELHAMID MOHAMED ABDELHAMID	40	Ver horario
ELI211	REDES ELECTRICAS I	INGENIERÍA ELÉCTRICA	1	MONTAÑA CHAPARRO JOHNY HERNÁN	40	Ver horario
ELI212	REDES ELECTRICAS II	INGENIERÍA ELÉCTRICA	1	FOURNIES LATORRE GASTON ANDRES	40	Ver horario
TEL315	REDES INALÁMBRICAS	ELECTRONICA	1	MARTINEZ VERDUGO JOSE MANUEL	40	Ver horario
IPD415	REDES ÓPTICAS WDM	ELECTRONICA	1	JARA CARVALLO NICOLAS ALONSO	20	Ver horario
REE001	RELAC. ESTUD.	DIRECCION DE ESTUDIO	1		0	Ver horario
 	2		0	Ver horario
 	3	NN	0	Ver horario
 	4		0	Ver horario
 	5	NN	0	Ver horario
 	6	NN	0	Ver horario
 	7		0	Ver horario
 	8	THOMET ISLA FRANZ ANDRES	0	Ver horario
 	9	NN	0	Ver horario
 	10	NN	0	Ver horario
 	11	NN	0	Ver horario
 	12	NN	0	Ver horario
 	13	NN	0	Ver horario
 	14		0	Ver horario
 	15		0	Ver horario
 	16		0	Ver horario
 	17	NN	0	Ver horario
 	18		0	Ver horario
 	19		0	Ver horario
 	20		0	Ver horario
 	21		0	Ver horario
 	22		0	Ver horario
 	23		0	Ver horario
 	24		0	Ver horario
 	25		0	Ver horario
 	26		0	Ver horario
 	27		0	Ver horario
 	28		0	Ver horario
 	29		0	Ver horario
 	30		0	Ver horario
 	31	NN	0	Ver horario
 	32		0	Ver horario
 	33		0	Ver horario
 	34	PEREZ RIOS DARWIN MAURICIO	0	Ver horario
HRW151	RELACIONES INTERPERSONALES	ESTUDIOS HUMANISTICOS	1	VERGARA SAAVEDRA MARIO	40	Ver horario
IWM255	RESISTENCIA DE MATERIALES GENERALES	INGENIERÍA MECÁNICA	1	GONZALEZ BAQUEDANO GUILLERMO	40	Ver horario
IPD482	ROBOTICA MOVIL PROBABILISTICA	ELECTRONICA	1	AUAT CHEEIN FERNANDO ALFREDO	20	Ver horario
TEL312	SEGURIDAD EN REDES DE COMPUTADORES	ELECTRONICA	1	DONDERS ORELLANA ERIC JOSE	40	Ver horario
HRW160	SEM. DE LA TEORIA POLITICA	ESTUDIOS HUMANISTICOS	1	IOMMI AMUNATEGUI XIMENA	40	Ver horario
IPD439	SEMINARIO AVANZADO DE COMPUTADORES	ELECTRONICA	1	VOURKAS IOANNIS	10	Ver horario
IPD446	SEMINARIO AVANZADO DE TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES(TIC)	ELECTRONICA	1	AHMED ABDELHAMID MOHAMED ABDELHAMID	20	Ver horario
MEC341	SEMINARIO DE ECONOMIA ENERGETICA	INGENIERÍA MECÁNICA	1	YUNGE DUCAUD ROBERTO	40	Ver horario
FIS299	SEMINARIO DE GRADO	FISICA	1	PACHECO DOLL MONICA JEANETTE	20	Ver horario
MAT598	SEMINARIO DE INVESTIGACION I	MATEMATICA	1	OSORIO SALGADO FELIPE ALBERTO	5	Ver horario
 	2	CARREÑO GODOY NICOLÁS	5	Ver horario
 	3	ALARCON ARANEDA SALOMON DIOGENES	5	Ver horario
ICI309	SEMINARIO DE MEMORIA	INFORMATICA	1	HEVIA RODRIGUEZ LUIS	40	Ver horario
INF383	SEMINARIO DE MODELOS Y MÉTODOS CUANTITATIVOS	INFORMATICA	2	PEZOA RIVERA RAQUEL ANDREA	40	Ver horario
INF363	SEMINARIO DE SISTEMAS Y GESTION	INFORMATICA	1	CASTRO VALDEBENITO CARLOS	40	Ver horario
MAT491	SEMINARIO DE TESIS I	MATEMATICA	1	GUZMAN MELENDEZ PATRICIO RICARDO	40	Ver horario
 	2	CARREÑO GODOY NICOLÁS	40	Ver horario
 	3	QUAAS BERGER ALEXANDER	40	Ver horario
 	4	QUAAS BERGER ALEXANDER	40	Ver horario
 	5	LECAROS LIRA RODRIGO ANTONIO	40	Ver horario
 	6	ITURRIAGA PASTENE LEONELO PATRICIO	40	Ver horario
 	7	BRICEÑO ARIAS LUIS MANUEL	40	Ver horario
MAT492	SEMINARIO DE TESIS II	MATEMATICA	1	KARKULIK . MICHAEL	40	Ver horario
 	2	BRICEÑO ARIAS LUIS MANUEL	40	Ver horario
 	3	OSORIO SALGADO FELIPE ALBERTO	0	Ver horario
ELI376	SEMINARIO DE TITULACIÓN	INGENIERÍA ELÉCTRICA	1	SCHURCH BRANDT ROGER STEFFAN	40	Ver horario
ICN347	SEMINARIO INVESTIG. OPERACIONES	INDUSTRIAS	1	YURASZECK ESPINOZA FRANCISCO JAVIER	40	Ver horario
MAT417	SERIES DE TIEMPO	MATEMATICA	1	VALLEJOS ARRIAGADA RONNY OBED	0	Ver horario
MAT267	SERIES DE TIEMPO I	MATEMATICA	1	TAPIA CARO JOSE ANDRES	40	Ver horario
ELI213	SIMULACION EN INGENIERIA ELECTRICA	INGENIERÍA ELÉCTRICA	1	GIL SAGAS ESTEBAN MANUEL	40	Ver horario
ICN393	SIMULACIÓN DE MERCADOS	INDUSTRIAS	1	YAÑEZ MARTINEZ DIEGO IGNACIO	40	Ver horario
TEL341	SIMULACIÓN DE REDES	ELECTRONICA	1	JARA CARVALLO NICOLAS ALONSO	40	Ver horario
ARQ341	SISTEMAS CONSTRUCTIVOS BÁSICOS	ARQUITECTURA	1	BARROS LAFUENTE LUIS PABLO	40	Ver horario
 	2	SARABIA FUENTES GUSTAVO	40	Ver horario
ARQ541	SISTEMAS CONSTRUCTIVOS COMPLEJOS	ARQUITECTURA	1	SOTO ARRIAGADA EMILIO ALEJANDRO	40	Ver horario
ICN292	SISTEMAS DE INFORMACION PARA LA GESTION	INDUSTRIAS	1	FAVEREAU URQUIZA RAFAEL ALEJ	40	Ver horario
 	2	FAVEREAU URQUIZA RAFAEL ALEJ	40	Ver horario
ICS016	SISTEMAS DE INFORMACION PARA LA GESTION	INGENIERÍA COMERCIAL	1	YAÑEZ WARNER PATRICIO	40	Ver horario
TEL231	SISTEMAS DE TELECOMUNICACIONES I	ELECTRONICA	2	ZAÑARTU SALAS MATIAS	55	Ver horario
ELO211	SISTEMAS DIGITALES	ELECTRONICA	2	CARVAJAL BARRERA GONZALO ANDRES	80	Ver horario
MAT341	SISTEMAS DINAMICOS	MATEMATICA	1	AGUIRRE OLEA PABLO	10	Ver horario
ELI240	SISTEMAS ELECTRICOS DE POTENCIA A	INGENIERÍA ELÉCTRICA	1	HINOJOSA MATEUS VICTOR HUGO	40	Ver horario
ELO281	SISTEMAS ELECTROMECANICOS	ELECTRONICA	1	PONTT OLIVARES JORGE ANTONIO	60	Ver horario
ILI246	SISTEMAS OPERATIVOS	INFORMATICA	1	BONNAIRE . XAVIER EMMANUEL	40	Ver horario
INF246	SISTEMAS OPERATIVOS	INFORMATICA	1	BONNAIRE . XAVIER EMMANUEL	60	Ver horario
HRW150	SOCIOLOGIA INDUSTRIAL	ESTUDIOS HUMANISTICOS	1	VERGARA SAAVEDRA MARIO	40	Ver horario
MET320	SOLDADURA	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	TELLO ARAYA KAREM EVA	40	Ver horario
MRA451	SOSTENIBILIDAD EN LA EDIFICACIÓN	ARQUITECTURA	1	SILLS GARRIDO PABLO	20	Ver horario
IAO361	SUELO Y FUNDACIONES	ARQUITECTURA	1	NN	60	Ver horario
IWQ374	SUPERVISION DE PERSONAL	INGENIERÍA QUíMICA Y AMBIENTAL	1	RAMIREZ LIVINGSTON DANIEL ALBERTO	50	Ver horario
MAT441	Seminario de Investigación I	MATEMATICA	1	BRICEÑO ARIAS LUIS MANUEL	5	Ver horario
 	2	MERCADO SAUCEDO ALBERTO CARLOS	5	Ver horario
 	3	GUZMAN MELENDEZ PATRICIO RICARDO	5	Ver horario
 	4	QUAAS BERGER ALEXANDER	40	Ver horario
 	5	LECAROS LIRA RODRIGO ANTONIO	40	Ver horario
 	6	ITURRIAGA PASTENE LEONELO PATRICIO	40	Ver horario
MAT443	Seminario de Investigación II	MATEMATICA	1	GUZMAN MELENDEZ PATRICIO RICARDO	5	Ver horario
 	2	GUZMAN MELENDEZ PATRICIO RICARDO	5	Ver horario
 	3	CARREÑO GODOY NICOLÁS	5	Ver horario
EFI115	TAEKWONDO	DEFIDER	1	AGUILAR GAJARDO SEBASTIAN ANDRES	40	Ver horario
ARQ451	TALLER AVANZADO I	ARQUITECTURA	1	HORMAZABAL POBLETE NINA AMOR	40	Ver horario
 	2	LEON CANALES JORGE ENRIQUE	40	Ver horario
 	3	CACERES CORVALAN KATHERINE JACQUELINE	40	Ver horario
ARQ452	TALLER AVANZADO II	ARQUITECTURA	1	HORMAZABAL POBLETE NINA AMOR	40	Ver horario
 	2	LEON CANALES JORGE ENRIQUE	40	Ver horario
 	3	CACERES CORVALAN KATHERINE JACQUELINE	40	Ver horario
ARQ551	TALLER AVANZADO III	ARQUITECTURA	1	HORMAZABAL POBLETE NINA AMOR	40	Ver horario
 	2	LEON CANALES JORGE ENRIQUE	40	Ver horario
 	3	CACERES CORVALAN KATHERINE JACQUELINE	40	Ver horario
 	4	GALVEZ HUERTA MIGUEL ANGEL	40	Ver horario
ARQ352	TALLER ESPACIO Y TECTÓNICA	ARQUITECTURA	1	CASTRO GONZALEZ CARLOS JULIO	40	Ver horario
ARQ051	TALLER AVANZADO IV	ARQUITECTURA	1	HORMAZABAL POBLETE NINA AMOR	40	Ver horario
 	2	LEON CANALES JORGE ENRIQUE	40	Ver horario
 	3	CACERES CORVALAN KATHERINE JACQUELINE	40	Ver horario
 	4	GALVEZ HUERTA MIGUEL ANGEL	40	Ver horario
III303	TALLER DE COACHING PARA EMPRENDEDORES	INDUSTRIAS	1	GOMEZ RODRIGUEZ DANIEL ENRIQUE	40	Ver horario
 	2	GOMEZ RODRIGUEZ DANIEL ENRIQUE	40	Ver horario
 	3	SANCHEZ GIRALDEZ RODRIGO LUIS	40	Ver horario
 	4	GOMEZ RODRIGUEZ DANIEL ENRIQUE	40	Ver horario
ICS181	TALLER DE CREATIVIDAD Y COMUNICACIÓN EFECTIVA	INGENIERÍA COMERCIAL	1	LOPEZ YAÑEZ JAVIERA ANDREA	40	Ver horario
 	2	SOTO YAÑEZ CARLOS HUMBERTO	40	Ver horario
 	3	SALAZAR QUINTEROS DANIELA ALEJANDRA	40	Ver horario
 	4	GALLARDO BURGOS PABLO ANDRES	40	Ver horario
 	5	ALDAYUZ RODRIGUEZ CRISTIAN	40	Ver horario
ARQ251	TALLER DE ESPACIO URBANO	ARQUITECTURA	1	SOTO CARO MARCELA ANDREA	70	Ver horario
IWQ386	TALLER DE INGENIERIA QUIMICA II	INGENIERÍA QUíMICA Y AMBIENTAL	1	NN	40	Ver horario
IQA321	TALLER DE INGENIERÍA AMBIENTAL I	INGENIERÍA QUíMICA Y AMBIENTAL	1	BONERT PUIG PAMELA ALEJANDRA	40	Ver horario
ILN010	TALLER DE INGENIERÍA INDUSTRIAL I	INDUSTRIAS	1	PEDRALS SCHENCK BEATE KATHARINA	40	Ver horario
 	2	PEDRALS SCHENCK BEATE KATHARINA	40	Ver horario
 	3	BUSTOS CASTRO MARIA ALEJANDRA	40	Ver horario
 	8	PEDRALS SCHENCK BEATE KATHARINA	40	Ver horario
ILN011	TALLER DE INGENIERÍA INDUSTRIAL II	INDUSTRIAS	1	NN	40	Ver horario
ILN012	TALLER DE INGENIERÍA INDUSTRIAL III	INDUSTRIAS	1	NN	40	Ver horario
 	2	NN	40	Ver horario
 	4	NN	40	Ver horario
IQA030	TALLER DE INGENIERÍA QUIMICA III	INGENIERÍA QUíMICA Y AMBIENTAL	1	ESPERGUES ZUÑIGA FERNANDO JAIME	40	Ver horario
IQA010	TALLER DE INGENIERÍA QUÍMICA I	INGENIERÍA QUíMICA Y AMBIENTAL	1	ESPERGUES ZUÑIGA FERNANDO JAIME	40	Ver horario
IQA020A	TALLER DE INGENIERÍA QUÍMICA II	INGENIERÍA QUíMICA Y AMBIENTAL	1	ESPERGUES ZUÑIGA FERNANDO JAIME	40	Ver horario
IWG394	TALLER DE MEMORIA MULTIDISCIPLINARIA I	DIRECCION GRAL. DOCENCIA	1	EQUIPO	40	Ver horario
IWG395	TALLER DE MEMORIA MULTIDISCIPLINARIA II	DIRECCION GRAL. DOCENCIA	1	EQUIPO	40	Ver horario
ARQ331	TALLER DE MÉTODOS COMPUTACIONALES EN ARQUITECTURA	ARQUITECTURA	1	GONZALEZ BOHME LUIS FELIPE	57	Ver horario
 	2	VALENZUELA ASTUDILLO EDUARDO ANTONIO	40	Ver horario
INF324	TALLER DE PRODUCCION DE SOFTWARE	INFORMATICA	1	MARQUEZ ORTEGA GASTON PATRICIO	40	Ver horario
IDP111	TALLER DE PRODUCTOS I	Ingeniería en Diseño	1	BRIEDE WESTERMEYER JUAN CARLOS	40	Ver horario
IDP113	TALLER DE PRODUCTOS III	Ingeniería en Diseño	1	ROJO VENEGAS GUSTAVO	40	Ver horario
IDP115	TALLER DE PRODUCTOS V	Ingeniería en Diseño	1	LOPEZ GARCIA GABRIELA	40	Ver horario
IDP117	TALLER DE PRODUCTOS VII	Ingeniería en Diseño	1	ARENAS PINTO VICENTE	40	Ver horario
HFW141	TALLER DE PSICOLOGIA DE LA CREATIVIDAD	ESTUDIOS HUMANISTICOS	1	HONORATO FALCON XIMENA MARIA	40	Ver horario
MET391	TALLER DE TITULACIÓN	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	VERA ROMAN MARCO ANTONIO	40	Ver horario
CIV397	TALLER DE TITULACIÓN I	OBRAS CIVILES	1	CATALAN MONDACA PATRICIO ANDRES	40	Ver horario
IWQ395	TALLER DE TITULACIÓN I	INGENIERÍA QUíMICA Y AMBIENTAL	1	EQUIPO	40	Ver horario
IWQ396	TALLER DE TITULACIÓN II	INGENIERÍA QUíMICA Y AMBIENTAL	1	EQUIPO	40	Ver horario
IDP118	TALLER DE TITULO	Ingeniería en Diseño	1	MONTECCHI . TIZIANO	5	Ver horario
 	2	MADARIAGA BRAVO LEONARDO ANDRES	5	Ver horario
 	3	NIKULIN CHANDIA CHRISTOPHER	5	Ver horario
 	4	DOROCHESI FERNANDOIS MARIO	5	Ver horario
 	5	LOPEZ GARCIA GABRIELA	2	Ver horario
ICN398	TALLER DE TITULO I	INDUSTRIAS	1	CAMINO DIAZ TAMARA PAOLA	40	Ver horario
 	2	SANTANDER ASTORGA PAULINA	40	Ver horario
 	3	SANTANDER ASTORGA PAULINA	40	Ver horario
ICS029	TALLER DE TITULO I	INGENIERÍA COMERCIAL	1	SANTANDER ASTORGA PAULINA	40	Ver horario
ICN399	TALLER DE TITULO II	INDUSTRIAS	1	SALAZAR ALBORNOZ RODOLFO IGNACIO	5	Ver horario
 	2	FERNANDEZ ROBIN ERNESTO CRISTOBAL	5	Ver horario
 	3	MOYA ALFARO JOHANA SOLANGE	5	Ver horario
 	4	FUENTES ZEPEDA RAUL ANTONIO	5	Ver horario
 	5	FUENTES CASTILLO ANDRES HERNAN	5	Ver horario
 	6	KRISTJANPOLLER RODRIGUEZ WERNER DAVID	5	Ver horario
 	7	STEGMAIER BRAVO RAUL	5	Ver horario
 	8	VIVEROS GUNCKEL PABLO ANDRES	5	Ver horario
 	9	ESCALONA RODRIGUEZ PABLO	5	Ver horario
 	10	FAVEREAU URQUIZA RAFAEL ALEJ	5	Ver horario
 	11	KRISTJANPOLLER RODRIGUEZ FREDY ARIEL	5	Ver horario
 	12	SAAVEDRA RODRIGUEZ OSCAR JULIO	5	Ver horario
 	13	KRISTJANPOLLER RODRIGUEZ FREDY ARIEL	5	Ver horario
 	14	SAAVEDRA RODRIGUEZ OSCAR JULIO	5	Ver horario
 	15	AMESTICA HERNANDEZ GONZALO DAVID	5	Ver horario
 	16	DEMARCO BULL RODRIGO ANDRES	5	Ver horario
 	17	YAÑEZ SANDIVARI LUIS	5	Ver horario
 	18	KRISTJANPOLLER RODRIGUEZ WERNER DAVID	5	Ver horario
 	19	KRISTJANPOLLER RODRIGUEZ FREDY ARIEL	5	Ver horario
 	20	KRISTJANPOLLER RODRIGUEZ WERNER DAVID	5	Ver horario
 	21	DEMARCO BULL RODRIGO ANDRES	5	Ver horario
 	22	DE LA FUENTE MUÑOZ FRANCISCO JAVIER	5	Ver horario
 	23	FAVEREAU URQUIZA RAFAEL ALEJ	5	Ver horario
 	24	SALAZAR ALBORNOZ RODOLFO IGNACIO	5	Ver horario
 	25	YAÑEZ MARTINEZ DIEGO IGNACIO	5	Ver horario
 	26	CONTRERAS RODRIGUEZ JORGE OMAR	5	Ver horario
 	27	LOPEZ CAMPOS MONICA ALEJANDRA	5	Ver horario
 	28	GARCÍA SEPÚLVEDA IGNACIO JAVIER	5	Ver horario
ICS032	TALLER DE TITULO II	INGENIERÍA COMERCIAL	1	OSORIO ZELADA HUGO ANTONIO	5	Ver horario
 	2	PESCE SANTANA GIOVANNI	5	Ver horario
 	3	VALENZUELA OYANEDER LIONEL ANDRES	5	Ver horario
 	4	SOTO YAÑEZ CARLOS HUMBERTO	5	Ver horario
 	5	CEA VALENCIA JORGE MAURICIO	5	Ver horario
 	6	TAPIA GERTOSIO JUAN FRANCISCO	5	Ver horario
 	7	RUBIO ROMERO PATRICIO	5	Ver horario
FIS260	TALLER DISEÑO DE EXPERIMENTOS PARA LA ENSEÑANZA DE	FISICA	1	SANCHEZ ESPINOZA JAVIERA PATRICIA	40	Ver horario
MEC376	TALLER EMPRESARIAL	INGENIERÍA MECÁNICA	2	BREGANTE BACELLI ANDRES TOMAS	40	Ver horario
 	3	VALDENEGRO OYANEDER RENE ANTONIO	40	Ver horario
ARQ252	TALLER ESPACIO INTERMEDIO Y CLIMA	ARQUITECTURA	1	CARRASCO WALBURG CAROLINA ANDREA	40	Ver horario
ARQ101	TALLER INTRODUCCION A LA ARQUITECTURA I	ARQUITECTURA	1	SOLIS FIGUEROA RAUL ALEJANDRO	100	Ver horario
MRA500	TALLER METODOLOGÍA I	ARQUITECTURA	1	HURTADO SALDIAS MARCELA	20	Ver horario
 	1	GALVEZ HUERTA MIGUEL ANGEL	20	Ver horario
 	1	HORMAZABAL POBLETE NINA AMOR	20	Ver horario
 	1	SILLS GARRIDO PABLO	20	Ver horario
 	1	CARRASCO WALBURG CAROLINA ANDREA	20	Ver horario
ARQ351	TALLER MODELACIÓN DEL ESPACIO	ARQUITECTURA	1	GONZALEZ BOHME LUIS FELIPE	45	Ver horario
ELI360	TECNICAS DE ALTA TENSION I	INGENIERÍA ELÉCTRICA	1	RIOS VIELMA JAVIER IGNACIO	40	Ver horario
ELI362	TECNOLOGIA DE ALTA TENSION	INGENIERÍA ELÉCTRICA	1	MONTAÑA CHAPARRO JOHNY HERNÁN	40	Ver horario
ICM312	TECNOLOGIA DE LA COMBUSTION	INGENIERÍA MECÁNICA	1	CONTRERAS RODRIGUEZ JORGE OMAR	40	Ver horario
CON253	TECNOLOGIA DE LA MADERA Y LABORATORIO	OBRAS CIVILES	1	CARMONA CERDA RENE	50	Ver horario
CIV251	TECNOLOGIA DE MATERIALES	OBRAS CIVILES	1	DELGADILLO STURLA RODRIGO	60	Ver horario
CON252	TECNOLOGIA DEL HORMIGON Y LABORATORIO	OBRAS CIVILES	1	CARMONA MALATESTA SERGIO	50	Ver horario
IWC205	TECNOLOGIA Y PROCESAMIENTO DE POLÍMEROS	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	ROMERO VILLARROEL FRANCISCO FELIX	40	Ver horario
MEC160	TECNOLOGÍA DE TALLER	INGENIERÍA MECÁNICA	1	MENA YANSSEN RAFAEL	40	Ver horario
 	2	MENA YANSSEN RAFAEL	40	Ver horario
ELO346	TELECOMUNICACIONES INALAMBRICAS	ELECTRONICA	1	CARVAJAL GUERRA RODRIGO JAVIER	40	Ver horario
IPD461	TELECOMUNICACIONES INALAMBRICAS AVANZADO	ELECTRONICA	1	CARVAJAL GUERRA RODRIGO JAVIER	20	Ver horario
EFI113	TENIS	DEFIDER	1	CABELLO CONTRERAS ENRIQUE ALEJANDRO	30	Ver horario
 	2	CABELLO CONTRERAS ENRIQUE ALEJANDRO	40	Ver horario
 	3	CABELLO CONTRERAS ENRIQUE ALEJANDRO	30	Ver horario
EFI114	TENIS DE MESA	DEFIDER	1	DEL SOLAR VIDELA HUGO ROBERTO	30	Ver horario
 	2	DEL SOLAR VIDELA HUGO ROBERTO	30	Ver horario
FIS471	TEORIA CUANTICA DE CAMPOS II	FISICA	1	SCHMIDT ANDRADE IVAN EUGENIO	20	Ver horario
MAT431	TEORIA DE PROBABILIDADES	MATEMATICA	1	NN	40	Ver horario
MAT263	TEORIA DE PROBABILIDADES Y PROCESOS ESTO	MATEMATICA	1	ALEGRIA JIMENEZ ALFREDO ANTONIO	40	Ver horario
ELO102	TEORIA DE REDES ELECTRICAS I	ELECTRONICA	1	YUZ EISSMANN JUAN IGNACIO	80	Ver horario
ELO103	TEORIA DE REDES ELECTRICAS II	ELECTRONICA	1	RAMIREZ ESTAY HECTOR MIGUEL	45	Ver horario
ELO321	TEORIA DE SISTEMAS OPERATIVOS	ELECTRONICA	1	MALONNEK WETZEL RUDY SERGIO	40	Ver horario
HRW202	TEORIA DEL CINE	ESTUDIOS HUMANISTICOS	1	BARRIA TRONCOSO ALFREDO ALEJANDRO	40	Ver horario
 	2	BARRIA TRONCOSO ALFREDO ALEJANDRO	40	Ver horario
MAT576	TEORIA ESTADISTICA	MATEMATICA	1	VALLEJOS ARRIAGADA RONNY OBED	40	Ver horario
ELO378	TEORIA MODERNA DE CONTROL LINEAL	ELECTRONICA	1	SUAREZ SOTOMAYOR ALEJANDRO	40	Ver horario
MAT043	TEORÍA DE PROBABILIDAD Y APLICACIONES	MATEMATICA	1	HENRIQUEZ CASTRO ESTEBAN	50	Ver horario
INF260	TEORÍA DE SISTEMAS	INFORMATICA	2	RIVAS ECHEVERRIA FRANCKLIN IVAN	50	Ver horario
 	3	RIVAS ECHEVERRIA FRANCKLIN IVAN	50	Ver horario
ARQ211	TEORÍA E HISTORIA DE LA CIUDAD	ARQUITECTURA	1	HURTADO SALDIAS MARCELA	70	Ver horario
 	2	JIMÉNEZ BUSTOS TATIANA	40	Ver horario
ICS142	TEORÍA FINANCIERA	INGENIERÍA COMERCIAL	1	MARCHANT GARCIA JAIME	40	Ver horario
 	2	GALLARDO RAMIREZ INGRID	40	Ver horario
 	3	ZURITA ROMAN IVAN	40	Ver horario
 	4	GALLARDO RAMIREZ INGRID	40	Ver horario
 	5	MARCHANT GARCIA JAIME	40	Ver horario
ARQ311	TEORÍA Y HISTORIA DE LA REPRESENTACIÓN EN ARQUITEC	ARQUITECTURA	1	MAINO ANSALDO SANDRO	50	Ver horario
IWQ111	TERMODINAMICA	INGENIERÍA QUíMICA Y AMBIENTAL	1	DE LA FUENTE BADILLA JUAN CAROL	70	Ver horario
IWM210	TERMODINAMICA GENERAL Y LABORATORIO	INGENIERÍA MECÁNICA	3	CASTRO CASTRO JUAN PABLO	60	Ver horario
 	4	CASTRO CASTRO JUAN PABLO	60	Ver horario
ILQ212	TERMODINAMICA PARA INGENIEROS QUIMICOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	DE LA FUENTE BADILLA JUAN CAROL	60	Ver horario
FIS230	TERMODINAMICA Y MECANICA ESTADISTICA	FISICA	1	PEÑA RECABARREN FRANCISCO	40	Ver horario
MEC110	TERMODINÁMICA	INGENIERÍA MECÁNICA	1	TOLEDO TORRES MARIO GONZALO	40	Ver horario
MEC210	TERMODINÁMICA APLICADA	INGENIERÍA MECÁNICA	1	OLGUIN ASTUDILLO HERNAN ANDRES	40	Ver horario
IQA211	TERMODINÁMICA DE PROCESOS	INGENIERÍA QUíMICA Y AMBIENTAL	1	DE LA FUENTE BADILLA JUAN CAROL	70	Ver horario
MET136	TERMODINÁMICA METALÚRGICA I	INGENIERÍA METALÚRGICA Y DE MATERIALES	1	HENAO ZAPATA HECTOR MARIO	40	Ver horario
IQA212	TERMODINÁMICA PARA INGENIERÍA QUÍMICA	INGENIERÍA QUíMICA Y AMBIENTAL	1	DE LA FUENTE BADILLA JUAN CAROL	60	Ver horario
CON200	TOPOGRAFIA Y TALLER	OBRAS CIVILES	1	PACHECO CRUZ OSCAR HERNÁN	40	Ver horario
MEC398	TRABAJO DE TÍTULO DE INGENIERÍA MECÁNICA INDUSTRIAL	INGENIERÍA MECÁNICA	1	ROSALES HUERTA CARLOS EDUARDO	5	Ver horario
 	2	CABREJOS MARIN FRANCISCO	5	Ver horario
 	3	VALDENEGRO OYANEDER RENE ANTONIO	5	Ver horario
 	4	RHEINSCHMIDT . UDO RUDOLF	5	Ver horario
 	5	PERAZZO MAGGI FRANCO ORLANDO	5	Ver horario
 	6	SARIEGO PASTEN PEDRO MARCO	5	Ver horario
 	7	MENA YANSSEN RAFAEL	3	Ver horario
 	8	TOLEDO TORRES MARIO GONZALO	1	Ver horario
 	9	LASCANO FARAK SHEILA KATHERINE	2	Ver horario
 	10	PEREZ POZO LUIS CARLOS	2	Ver horario
 	11	NUÑEZ SEGOVIA JAIME HUMBERTO	3	Ver horario
 	12	ESPINOZA SILVA JAIME	3	Ver horario
INF309	TRABAJO DE TÍTULO I	INFORMATICA	1	HEVIA RODRIGUEZ LUIS	40	Ver horario
INF310	TRABAJO DE TÍTULO II	INFORMATICA	1	BONNAIRE . XAVIER EMMANUEL	5	Ver horario
 	2	TORRES LOPEZ CLAUDIO	5	Ver horario
 	3	LOPEZ CAMPOS MONICA ALEJANDRA	5	Ver horario
 	4	RIFF ROJAS MARIA CRISTINA	5	Ver horario
 	5	MONGE ANWANDTER RAUL	5	Ver horario
 	6	BUIL ARANDA CARLOS	5	Ver horario
 	7	HEVIA RODRIGUEZ LUIS	5	Ver horario
 	8	PEZOA RIVERA RAQUEL ANDREA	5	Ver horario
 	9	ALLENDE OLIVARES HECTOR	5	Ver horario
IDP302	TRABAJO EN EQUIPO Y LIDERAZGO	Ingeniería en Diseño	1	ARENAS PINTO VICENTE	40	Ver horario
IQA222	TRANSFERENCIA DE CALOR	INGENIERÍA QUíMICA Y AMBIENTAL	1	ORTIZ ROJAS ADRIAN ENRIQUE	40	Ver horario
IWM230	TRANSFERENCIA DE CALOR	INGENIERÍA MECÁNICA	1	OLGUIN ASTUDILLO HERNAN ANDRES	40	Ver horario
 	2	TOLEDO TORRES MARIO GONZALO	40	Ver horario
IWQ222	TRANSFERENCIA DE CALOR	INGENIERÍA QUíMICA Y AMBIENTAL	1	ORTIZ ROJAS ADRIAN ENRIQUE	40	Ver horario
MEC230	TRANSFERENCIA DE CALOR	INGENIERÍA MECÁNICA	1	OLGUIN ASTUDILLO HERNAN ANDRES	40	Ver horario
IWQ224	TRANSFERENCIA DE MATERIA	INGENIERÍA QUíMICA Y AMBIENTAL	1	ACUNA PEREZ CLAUDIO ABRAH	50	Ver horario
IMQ310	TRATAMIENTO DE GASES	INGENIERÍA QUíMICA Y AMBIENTAL	1	HANSEN KIRSTEIN KNUD HENRIK	40	Ver horario
IMQ311	TRATAMIENTO DE RILES	INGENIERÍA QUíMICA Y AMBIENTAL	1	DA SILVA ALVAREZ CRISTOPHER	0	Ver horario
FIS470	Teoría Cuántica de Campos I	FISICA	1	CVETIC - GORAZD	20	Ver horario
MEC399	TÍTULO DE INGENIERÍA CIVIL MECÁNICA	INGENIERÍA MECÁNICA	1	TOLEDO TORRES MARIO GONZALO	6	Ver horario
 	2	VALDENEGRO OYANEDER RENE ANTONIO	5	Ver horario
 	3	MENA YANSSEN RAFAEL	5	Ver horario
 	4	SARIEGO PASTEN PEDRO MARCO	5	Ver horario
 	5	GONZALEZ BAQUEDANO GUILLERMO	5	Ver horario
 	6	COOPER VILLAGRAN CHRISTOPHER	5	Ver horario
 	7	AMADOR DIAZ GERMAN JAVIER	5	Ver horario
 	8	RHEINSCHMIDT . UDO RUDOLF	5	Ver horario
 	9	FLORES MARADIAGA ALEX GEOVANNY	3	Ver horario
 	10	OLGUIN ASTUDILLO HERNAN ANDRES	5	Ver horario
 	11	ROSALES HUERTA CARLOS EDUARDO	1	Ver horario
 	12	ESPINOZA SILVA JAIME	2	Ver horario
 	13	BARRAZA VICENCIO RODRIGO SEBASTI	1	Ver horario
 	14	PEREZ POZO LUIS CARLOS	3	Ver horario
 	15	BORÉ BACIGALUPPI GUSTAVO IGNACIO	5	Ver horario
ICN357	USO DE SOFTWARE DE INGENIERIA INDUSTRIAL	INDUSTRIAS	1	FAVEREAU URQUIZA RAFAEL ALEJ	40	Ver horario
CON281	VIALIDAD II Y LABORATORIO	OBRAS CIVILES	1	WAHR DANIEL CARLOS	50	Ver horario
HRW103	VISION ESTETICA DEL QUEHACER HUMANO	ESTUDIOS HUMANISTICOS	1	BARRIA TRONCOSO ALFREDO ALEJANDRO	40	Ver horario
 	2	BARRIA TRONCOSO ALFREDO ALEJANDRO	40	Ver horario
 	3	BARRIA TRONCOSO ALFREDO ALEJANDRO	40	Ver horario
 	4	OLATE VALENZUELA SILVIO RENATO	40	Ver horario
 	5	OLATE VALENZUELA SILVIO RENATO	40	Ver horario
 	6	AYALA VELOSO JUAN GONZALO	40	Ver horario
 	7	AYALA VELOSO JUAN GONZALO	40	Ver horario
HRW102	VISION INMANENTE DEL QUEHACER HUMANO	ESTUDIOS HUMANISTICOS	1	IOMMI AMUNATEGUI XIMENA	40	Ver horario
 	2	IOMMI AMUNATEGUI XIMENA	40	Ver horario
 	3	ACHONDO MOYA PEDRO PABLO	40	Ver horario
 	4	GARCIA CONTRERAS IVAN ANDRES	40	Ver horario
 	5	GARCIA CONTRERAS IVAN ANDRES	40	Ver horario
 	6	GARCIA CONTRERAS IVAN ANDRES	40	Ver horario
 	7	GARCIA CONTRERAS IVAN ANDRES	40	Ver horario
HRW101	VISION TRASCENDENTE DEL QUEHACER HUMANO	ESTUDIOS HUMANISTICOS	1	CHATEAU CANTILLANA PIERRE FRANCISCO	40	Ver horario
 	2	CHATEAU CANTILLANA PIERRE FRANCISCO	40	Ver horario
 	3	CHATEAU CANTILLANA PIERRE FRANCISCO	40	Ver horario
 	4	CHATEAU CANTILLANA PIERRE FRANCISCO	40	Ver horario
 	5	MUÑOZ BUSTAMANTE EDUARDO	40	Ver horario
 	6	MUÑOZ BUSTAMANTE EDUARDO	40	Ver horario
 	7	MUÑOZ BUSTAMANTE EDUARDO	40	Ver horario
 	8	MUÑOZ BUSTAMANTE EDUARDO	40	Ver horario
 	9	ARACENA HREPIC FELIPE	40	Ver horario
IPD441	VISIÓN POR COMPUTADOR	ELECTRONICA	1	ZUÑIGA BARRAZA MARCOS DAVID	20	Ver horario
EFI116	VÓLEIBOL	DEFIDER	1	HECHT CHAU GERNOT	30	Ver horario
 	2	BOTAU MANCILLA JORGE EDUARDO	30	Ver horario
 	3	HECHT CHAU GERNOT	30	Ver horario
MAT061	ÁLGEBRA LINEAL	MATEMATICA	1	TOLEDO TORRES PATRICIO ALEJANDRO	40	Ver horario
 	2	GALVEZ DIAZ SEBASTIAN ANDRES	40	Ver horario
MATE20	ÁLGEBRA LINEAL	MATEMATICA	1	LOPEZ CEPEDA PATRICIA	40	Ver horario
 	2	VIDAL OLIVERO ALEJANDRO ANDRES	50	Ver horario
MAT060	ÁLGEBRA Y GEOMETRÍA	MATEMATICA	1	BARRIENTOS DIAZ SERGIO LUIS	40	Ver horario
 	2	ARANCIBIA BUSTOS ROGELIO MATHIAS	40	Ver horario
 	3	MUJICA TORRES JOSE PABLO	40	Ver horario
 	4	JIMENEZ HUGHES JUAN ENRIQUE	40	Ver horario
 	5	MERCADO SAUCEDO ALBERTO CARLOS	40	Ver horario
 	6	GAJARDO MIRANDA DIEGO FERNANDO	40	Ver horario
 	7	CONTRERAS BARRAZA FABIAN	40	Ver horario
MATE10	ÁLGEBRA Y GEOMETRÍA	MATEMATICA	1	NN	40	Ver horario
 	1	GONZALEZ YAÑEZ BETSABE DEL CARMEN	40	Ver horario
 	2	SZANTO NAREA IVAN	40	Ver horario
 	2	GONZALEZ YAÑEZ BETSABE DEL CARMEN	40	Ver horario
 	3	YANSEN NUNEZ SERGIO MANUEL	40	Ver horario
 	3	VILLAR SEPULVEDA EDGARDO ENRIQUE	40	Ver horario
 	4	GONZALEZ YAÑEZ BETSABE DEL CARMEN	40	Ver horario
 	4	BRICEÑO VALENCIA VERONICA ESTHER	40	Ver horario
 	5	YANSEN NUNEZ SERGIO MANUEL	40	Ver horario
 	5	GONZALEZ YAÑEZ BETSABE DEL CARMEN	40	Ver horario
 	6	NN	40	Ver horario
HRW133	ÉTICA Y ARGUMENTACIÓN CRÍTICA	ESTUDIOS HUMANISTICOS	1	ZUCHEL LOVERA LORENA KATHERINE	40	Ver horario
 	2	ZUCHEL LOVERA LORENA KATHERINE	40	Ver horario
 	3	IOMMI AMUNATEGUI XIMENA	40	Ver horario
 	4	IOMMI AMUNATEGUI XIMENA	40	Ver horario